### DISCUSSION TITLE
Importing toml with Typescript

### DISCUSSION THREAD

**Discussion by brenc** [oven-sh/bun#12271] [Q&A]
Given the following:
```typescript
import configFile from 'bun-test-config.toml';
```
Typescript says `Cannot find module 'bun-test-config.toml' or its corresponding type declarations.ts(2307)`

The only workaround I can think of is this:
```typescript
// @ts-expect-error - Bun supports toml natively.
import configFile from 'bun-test-config.toml';
```
Is there a better way?

**Comment by shiny** [comment]
As [documentation outlined](https://bun.sh/docs/bundler/loaders), you can define a  `"*.toml"` module in *.d.ts

```ts
declare module "*.toml" {
  const value: any;
  export default value;
}
```

However, the imported type remains `any`

**Comment by brenc** [comment]
I don't see anything about that in the docs you linked (I looked through all the docs before posting here of course). That works but only if you have just one config file. Here's a more complex example I tested:
```typescript
declare module '*.toml' {
  interface Owner {
    name: string;
    dob: string;
  }

  interface Database {
    enabled: boolean;
    ports: number[];
    data: (string | number)[][];
    temp_targets: {
      cpu: number;
      case: number;
    };
  }

  interface Server {
    ip: string;
    role: string;
  }

  interface Servers {
    alpha: Server;
    beta: Server;
  }

  interface TomlExample {
    title: string;
    owner: Owner;
    database: Database;
    servers: Servers;
  }

  const value: TomlExample;
  export default value;
}
```
```toml
title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
dob = "1979-05-27T07:32:00-08:00"

[database]
enabled = true
ports = [ 8000, 8001, 8002 ]
data = [ ["delta", "phi"], [3.14] ]
temp_targets = { cpu = 79.5, case = 72.0 }

[servers]

[servers.alpha]
ip = "10.0.0.1"
role = "frontend"

[servers.beta]
ip = "10.0.0.2"
role = "backend"
```
