### DISCUSSION TITLE
cloudflare dev workers doesnt work after migration from node to bun

### DISCUSSION THREAD

**Discussion by TArch64** [oven-sh/bun#14859] [Q&A] [answered]
Hi guys. I wanna try bun and migrated my app from node 20 to latest bun version but I my workers stopped working

I have everything in docker and my workers seems to start successfully but every request fails from browser (proxied by nginx) and from worker container using curl. It fails like server didnt start but it does

I keep my workers as monorepo and starts them using run command with filter

```sh
bun --filter @minino/worker-uploader dev
# "dev": "wrangler dev --ip 0.0.0.0 --persist-to /cloudflare/data",
```

here is logs
```
worker-uploader-1  | @minino/worker-uploader dev:
worker-uploader-1  | @minino/worker-uploader dev:  ⛅️ wrangler 3.78.2 (update available 3.83.0)
worker-uploader-1  | @minino/worker-uploader dev: ---------------------------------------------
worker-uploader-1  | @minino/worker-uploader dev:
worker-uploader-1  | @minino/worker-uploader dev: Using vars defined in .dev.vars
worker-uploader-1  | @minino/worker-uploader dev: Your worker has access to the following bindings:
worker-uploader-1  | @minino/worker-uploader dev: - R2 Buckets:
worker-uploader-1  | @minino/worker-uploader dev:   - r2: minino-dev
worker-uploader-1  | @minino/worker-uploader dev: - Vars:
worker-uploader-1  | @minino/worker-uploader dev:   - API_URL: "(hidden)"
worker-uploader-1  | @minino/worker-uploader dev:   - API_ACCESS_KEY: "(hidden)"
worker-uploader-1  | @minino/worker-uploader dev: [wrangler:inf] Ready on http://0.0.0.0:8787
[wrangler:inf] - http://127.0.0.1:8787
[wrangler:inf] - http://192.168.97.5:8787
[wrangler:inf] Updated and ready on http://0.0.0.0:46699
⎔ Starting local server...
```

Vite dev server in another container using same image works fine

I tried to run worker locally without docker and it cannot even start and fails with and without `--bun` option

Does anyone have thoughts why it dont work?

My config files:
```Dockerfile
FROM oven/bun:1.1.33-slim
WORKDIR /app
```

```yaml
x-app-common: &app-common
  restart: always
  stdin_open: true
  tty: true
  env_file:
    - .env

x-worker-common: &worker-common
  <<: *app-common
  image: minimo-bun
  tty: false
  volumes:
    - ./apps/workers:/app
    - ./tmp/cloudflare/data:/cloudflare/data
    - workers_node_modules:/app/node_modules
    - bun_cache:/root/.bun/install/cache

services:
  worker-uploader:
    <<: *worker-common
    command: bun --filter @minino/worker-uploader dev
```

```nginx
upstream worker-uploader {
  server worker-uploader:8787;
}

server {
  server_name local.minino.app;
  listen 80 default_server;
  index off;
  access_log off;

  location /workers/uploader {
    proxy_pass http://worker-uploader/;
  }
}
```

I dont like having both node and bun runtimes revert changes back to node for now
