### DISCUSSION TITLE
Installing packages for more than one architecture

### DISCUSSION THREAD

**Discussion by ammubhave** [oven-sh/bun#17917] [Q&A]
We currently use `yarn` with the `supportedArchitectures` option in yarnrc. This is because the dev machines are macs, but we run development containers using docker compose. This means all the JS packages need to work with both `darwin` so that they can called directly from host machine, and for `linux` so that they run inside the containers.
```
supportedArchitectures:
  libc:
    - glibc
    - musl
  os:
    - linux
    - darwin
```

While attempting to move to bun, I noticed that the containers would crash because of missing linux architecture-specific packages (e.g. sharp for nextjs).

Is there a similar way like `supportedArchitectures` for bun?
