### DISCUSSION TITLE
What paths should we cache in CI?

### DISCUSSION THREAD

**Discussion by PaulRBerg** [oven-sh/bun#18752] [Q&A] [answered]
When using Bun, the `actions/cache` GitHub Action [recommends](https://github.com/actions/cache/blob/5a3ec84eff668545956fd18022155c47e93e2684/examples.md#bun) caching only the `~/.bun/install/cache` path:

```yaml
- uses: actions/cache@v4
  with:
    path: |
      ~/.bun/install/cache
    key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
```

Is that correct and what you as maintainers of Bun would recommend, too?

If yes, why does `node_modules` not have to be cached?

**Comment by thelovekesh** [comment]
By caching `node_modules`, you'll be reusing the same ones over and over, which could lead to unexpected issues, such as Bun resolving dependencies incorrectly, failing to prune dependencies properly in previous versions, or other potential problems.

On the other hand, by caching Bun’s cache, Bun will regenerate the `node_modules` directory for you. During this process, it will rely on Bun’s cache, eliminating any possibility of corrupted `node_modules` or other unexpected issues.

Another use case to consider is lifecycle scripts. If you have pre- or post-install scripts, caching the `node_modules` would prevent the install command from running, which could cause unexpected behavior. But when you cache Bun’s cache, these issues are avoided with nearly no extra time since Bun package manager is blazingly fast ⚡.

**Comment by Jarred-Sumner** [comment, marked as answer]
> Is that correct and what you as maintainers of Bun would recommend, too?

Yes but probably `**/bun.lock` nowadays that we default to bun.lock.

```yaml
- uses: actions/cache@v4
  with:
    path: |
      ~/.bun/install/cache
    key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
```

> If yes, why does node_modules not have to be cached?

Generally, `bun install` is faster than the github actions cache.
