### DISCUSSION TITLE
Use with AWS Codeartifact

### DISCUSSION THREAD

**Discussion by beeb** [oven-sh/bun#4913] [Q&A] [answered]
I'm trying to setup a private org registry like so:

```toml
[install.scopes."@myorg"]
url = "https://somethingsomething.d.codeartifact.region.amazonaws.com/npm/foo/"
token = "$NPM_TOKEN"
```

And the .env file has the `NPM_TOKEN` defined. Yet the install doesn't work and bun reports that it fails to resolve the packages `@myorg/bar` with HTTP status code 400. 

The same token in an `.npmrc` works fine with `npm install`, and copy-pasting the token inside the toml file makes no difference.

Anyone managed to use codeartifact?
