### ISSUE TITLE
Windows: Feature request - install using junction symlinks

### ISSUE THREAD

**Issue by Hecatron** [oven-sh/bun#10146]
### What is the problem this feature would solve?

Saves disk space when installing to node_modules under windows

### What is the feature you are proposing to solve the problem?

I realise it's still early days yet with windows especially with all the current issues.
One of the features with pnpm is the use of junctions when installing files under windows to save disk space.
Under windows symlnks appear to be problematic so they use the junctions feature instead as a workaround.

  * https://pnpm.io/faq#does-it-work-on-windows
  * https://learn.microsoft.com/en-us/windows/win32/fileio/hard-links-and-junctions

So what this does is create a directory called D:\.pnpm-store\ or C:\.pnpm-store\ then link everything from there into the node_modules directory that's being installed into.
This then saves disk space and can act as a different from of global cache.

### What alternatives have you considered?

I did have a quick go with the Bun node module resolution, but I don't think thats a thing under windows yet
https://bun.sh/docs/runtime/autoimport

**Comment by Hecatron** [comment]
After recently coming back to this
What I've discovered is that under Windows bun will create hard links to the cache.
But only if the cache is on the same drive as the project.

To give an example

  * If the global cache is set to the default (C:\Users\<username>\.bun\install\cache)
  * And you create two projects on a D drive such as D:\apps\myapp1 D:\apps\myapp2
  * These apps will have independent copies of the downloaded dependencies within node_modules, using up disk space

If all of your projects sit on a D: drive for example, then you can work around this by creating a `C:\Users\<username>\.bunfig.toml` file
With the following content
```toml
[install.cache]
# the directory to use for the cache
dir = "D:/.bun-store"

# when true, don't load from the global cache.
# Bun may still write to node_modules/.cache
disable = false

# when true, always resolve the latest versions from the registry
disableManifest = false
```
This will then move the global cache to `D:\.bun-store` and hard link from there

Ideally bun should create a separate cache per drive in the same way pnpm does, but this will do for now
