### ISSUE TITLE
BUN_HOME env variable for bun

### ISSUE THREAD

**Issue by MMMMMoris** [oven-sh/bun#10152]
### What version of Bun is running?

1.1.3+2615dc742

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

## bunfig.toml seems unable to work on Windows
Here is my config
```toml
[install.cache]
# the directory to use for the cache
dir = "~/AppData/Local/Temp/bun/install/cache"

# when true, don't load from the global cache.
# Bun may still write to node_modules/.cache
disable = false

# when true, always resolve the latest versions from the registry
disableManifest = false
```
Command `bun install -g live-server` still installed live-server in ~/.bun, downloaded files cached in it as well.

### What is the expected behavior?

Command `bun install -g live-server` should follow what has been defined as `[install.cache]` in ~\.bunfig

### What do you see instead?

Command `bun install -g live-server` still installed live-server in ~/.bun, downloaded files cached in it as well.
