### ISSUE TITLE
Getting the following error once I'm setting up a @company scope for JetBrains Space registry (error: FailedToOpenSocket downloading package manifest)

### ISSUE THREAD

**Issue by zozobalogh0817** [oven-sh/bun#10184]
### What version of Bun is running?

1.1.3+2615dc742

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Create a package on JetBrains Space Registry and then define that in bunfig.toml as the following

[install.scopes]
"@company" = "https://username:password@https://npm.pkg.jetbrains.space/company/p/PROJECT_ID_ON_JB_SPACE/registry/"

### What is the expected behavior?

Download the package from the corresponding registry

### What do you see instead?

I'm getting the following error.
error: FailedToOpenSocket downloading package manifest

**Comment by zozobalogh0817** [comment]
I'm not sure what happened, I think it was a missconfiguration from my side, so I'm closing the ticket

This is the working configuration for me in `bunfig.toml`

```toml
[install.scopes]
company = "https://username:password@npm.pkg.jetbrains.space/company/p/PROJECT_ID_AT_SPACE/registry/"
```
