### ISSUE TITLE
bun `--filter` with test even if the tests fail, pass the GitHub Action

### ISSUE THREAD

**Issue by aralroca** [oven-sh/bun#10359]
### What version of Bun is running?

1.1.4+fbe2fe0c3

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

`bun run --filter 'my-package-1' --filter 'my-package-2' test` the GitHub action does not detect when it fails and goes green even if tests fail

To reproduce it create `github/workflows/test.yml` with:

```yml
name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Bunjs
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.4
      - name: Install dependencies
        run: bun install
      - run: bun run test
```

And add the test script in the global `package.json`:

```json
"scripts": {
  "test": "bun run --filter 'my-package-1' --filter 'my-package-2' test"
}
```

Add some failing test and push to main or do a PR to main and see the GH Action behavior.

### What is the expected behavior?

the GH Action should crash since you have set the failing test

### What do you see instead?

GH Action passes correctly but if you look at the logs the tests do not pass
