### ISSUE TITLE
`bun install` broke since v1.1.6 - gyp ERR! stack Error: Cannot find module './high-level-opt.js

### ISSUE THREAD

**Issue by tigitz** [oven-sh/bun#10608]
### What version of Bun is running?

v1.1.6

### What platform is your computer?

Github CI - System Linux 6.5.0-1018-azure

### What steps can reproduce the bug?

Use this github CI workflow:
```yaml
jobs:
  scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install deps
        run: bun install
 ```
 
 And this package.json
 
 ```json
{
  "dependencies": {
    "@percy/cli-command": "^1.27.2",
    "dotenv": "^16.3.1",
    "execa": "^8.0.1",
    "node-ssh": "^13.1.0"
  }
}
 ```

### What is the expected behavior?

```
Run bun install
bun install v1.1.5 (b257a309)
 Resolving dependencies
 Resolved, downloaded and extracted [2]
 Saved lockfile

 + @clickhouse/client@0.2.7
 + @percy/cli-command@1.27.6
 + dotenv@16.3.1
 + execa@8.0.1
 + node-fetch@3.3.2
 + node-ssh@13.1.0
 + twig@1.17.1

 138 packages installed
```

### What do you see instead?

```
Run bun install
bun install v1.1.6
 Resolving dependencies
 Resolved, downloaded and extracted [2]
gyp info it worked if it ends with ok
gyp info using node-gyp@10.1.0
gyp info using node@20.12.2 | linux | x64
gyp info find Python using Python version 3.10.12 found at "/usr/bin/python3"
gyp ERR! configure error 
gyp ERR! stack Error: Cannot find module './high-level-opt.js'
gyp ERR! stack Require stack:
gyp ERR! stack - /tmp/bunx-1001-node-gyp@latest/node_modules/tar/lib/create.js
gyp ERR! stack - /tmp/bunx-1001-node-gyp@latest/node_modules/tar/index.js
gyp ERR! stack - /tmp/bunx-1001-node-gyp@latest/node_modules/node-gyp/lib/install.js
gyp ERR! stack - /tmp/bunx-1001-node-gyp@latest/node_modules/node-gyp/lib/node-gyp.js
gyp ERR! stack - /tmp/bunx-1001-node-gyp@latest/node_modules/node-gyp/bin/node-gyp.js
gyp ERR! stack at Module._resolveFilename (node:internal/modules/cjs/loader:1143:1[5](github-project/job/24345947817#step:5:6))
gyp ERR! stack at Module._load (node:internal/modules/cjs/loader:984:27)
gyp ERR! stack at Module.require (node:internal/modules/cjs/loader:1231:19)
gyp ERR! stack at require (node:internal/modules/helpers:179:18)
gyp ERR! stack at Object.<anonymous> (/tmp/bunx-1001-node-gyp@latest/node_modules/tar/lib/create.js:4:13)
gyp ERR! stack at Module._compile (node:internal/modules/cjs/loader:13[6](github-project/job/24345947817#step:5:7)9:14)
gyp ERR! stack at Module._extensions..js (node:internal/modules/cjs/loader:142[7](github-project/job/24345947817#step:5:8):10)
gyp ERR! stack at Module.load (node:internal/modules/cjs/loader:1206:32)
gyp ERR! stack at Module._load (node:internal/modules/cjs/loader:1022:12)
gyp ERR! stack at Module.require (node:internal/modules/cjs/loader:1231:19)
gyp ERR! System Linux 6.5.0-101[8](github-project/job/24345947817#step:5:9)-azure
gyp ERR! command "/opt/hostedtoolcache/node/20.12.2/x64/bin/node" "/tmp/bunx-[10](github-project/job/24345947817#step:5:11)01-node-gyp@latest/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/runner/work/.../node_modules/cpu-features
gyp ERR! node -v v20.[12](github-project/job/24345947817#step:5:13).2
gyp ERR! node-gyp -v v10.1.0
gyp ERR! not ok 

error: install script from "cpu-features" exited with 1
Error: Process completed with exit code 1.
```

### Additional information

I'm pinning bun to 1.1.5 for now as a workaround
```yaml
- uses: oven-sh/setup-bun@v1
  with:
    bun-version: 1.1.5
```
