### ISSUE TITLE
bun:test exclude node_modules when use '--coverage'

### ISSUE THREAD

**Issue by tialki** [oven-sh/bun#11613]
### What is the problem this feature would solve?

When run test, exclude node_modules when use '--coverage'

### What is the feature you are proposing to solve the problem?

Provider a config to exclude paths from coverage reports
```toml
[test]
coverageReportsExclude = ['node_modules']
```
