### ISSUE TITLE
connection error with bun, postgresql and Docker

### ISSUE THREAD

**Issue by maxime-aubry** [oven-sh/bun#11929]
### What version of Bun is running?

1.1.12

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

add this docker-compose.yml file :

``` YML
version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - .env

  auth:
    build:
      context: ./
      dockerfile: ./apps/auth/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules

  shadow-hunters-web-api:
    build:
      context: ./
      dockerfile: ./apps/shadow-hunters-web-api/Dockerfile
    ports:
      - 4000:5000
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - auth
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5436:5432
    volumes:
      #- ./db/data:/var/lib/postgresql/data
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "root", "-d", "shadow_hunters"]
      interval: 5s
      timeout: 10s
      retries: 5

  postgres_admin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - 15432:80
  
volumes:
  pgdata: {}
```

run this command :
`docker-componse up`

run this other command to run the project what use postgres :
`bun run start:dev auth`

### What is the expected behavior?

I would like to connect to the database please.

### What do you see instead?

Actually i get an error :

`[Nest] 2740  - 18/06/2024 00:31:54   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
Error: getaddrinfo ENOTFOUND postgres
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)`
    

### Additional information

Here is [the source code](https://github.com/maxime-aubry/shadow-hunters-web-api/tree/develop) if you want to test.

Docker Desktop : 4.31.1
Docker Compose version v2.27.0-desktop.2

Thanks for helping
