### ISSUE TITLE
[bun install] SegmentationFault with 443, 502, 404 error code

### ISSUE THREAD

**Issue by ild0tt0re** [oven-sh/bun#1211]
### Version

0.1.10

### Platform

Darwin mac.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

# MY CURRENT MONOREPO SETUP
- `Nx` dev tool (with `./apps/**` and `./libs/**` folders for packages)
- `pnpm` package manager (package.json in root folder `./`) -> see [package.txt](https://github.com/oven-sh/bun/files/9491722/package.txt)
- Private npm registry (Nexus) behind vpn
> ✅ ALL WORK!

# BUN INSTALLATION

1. Create config file only to add my registry URL (see `bunfig.toml` below)
2. run `bun install`
3. SegmentationFault at `0x0F5F9D6DFEFBFFFF`

## bunfig.toml
```toml
# Using scoped packages with bun install
[install.scopes]

# Scope name      The value can be a URL string or an object
"@mycompany" = { url = "https://packages.tools.mycompany.xyz/repository/npm-all/" }

[install]
registry = "https://packages.tools.mycompany.xyz/repository/npm-all/"

# Install for production? This is the equivalent to the "--production" CLI argument
production = false

# Don't actually install
dryRun = true

# Install optionalDependencies (default: true)
optional = true

# Install local devDependencies (default: true)
dev = true

# Install peerDependencies (default: false)
peer = false

# When using `bun install -g`, install packages here
globalDir = "~/.bun/install/global"

# When using `bun install -g`, link package bins here
globalBinDir = "~/.bun/bin"

# cache-related configuration
[install.cache]
# The directory to use for the cache
dir = "~/.bun/install/cache"

# Don't load from the global cache.
# Note: bun may still write to node_modules/.cache
disable = false

# Always resolve the latest versions from the registry
disableManifest = false


# Lockfile-related configuration
[install.lockfile]

# Print a yarn v1 lockfile
# Note: it does not load the lockfile, it just converts bun.lockb into a yarn.lock
print = "yarn"

# Path to read bun.lockb from
path = "bun.lockb"

# Path to save bun.lockb to
savePath = "bun.lockb"

# Save the lockfile to disk
save = true
```

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

Bun install dependencies correctly

### What do you see instead?

**COMPLETE LOG:** 
- [logs.txt](https://github.com/oven-sh/bun/files/9491663/logs.txt)

-------------

**END OUTPUT:**
SegmentationFault at 0x0F5F9D6DFEFBFFFF

----- bun meta -----
Bun v0.1.10 (fe7180bc) macOS x64 21.6.0
InstallCommand: bunfig 
HTTP: 1943
Elapsed: 43494ms | User: 2505ms | Sys: 3232ms
RSS: 0.60GB | Peak: 0.60GB | Commit: 1.02GB | Faults: 975
----- bun meta -----

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
