### ISSUE TITLE
Crash in `fs.readFile` when running `nuxt prepare` inside Docker container

### ISSUE THREAD

**Issue by FelipeSanchezCalzada** [oven-sh/bun#12129]
### How can we reproduce the crash?

My Dockerfile:
```Dockerfile
FROM oven/bun:1-alpine as build

WORKDIR /app
COPY . /app

RUN bun install
RUN bun run build

FROM oven/bun:1-slim

WORKDIR /app
COPY --from=build /app/.output ./

EXPOSE 3000

ENV HOST=0.0.0.0 PORT=3000 NODE_ENV=production

CMD ["bun","/app/server/index.mjs"]

```

My .gitlab-ci.yaml
```yaml
variables:
  DOCKER_PRIVATE_REGISTRY: docker-internal.felipesanchezweb.es
  BASE_IMAGE_TAG: $DOCKER_PRIVATE_REGISTRY/felipesanchezweb-nuxt
  IMAGE_TAG: $BASE_IMAGE_TAG:$CI_COMMIT_REF_SLUG
  IMAGE_TAG_LATEST: $BASE_IMAGE_TAG:latest

  SSH_HOST: 192.1.30.0

stages:
#  - build
  - dockerize
  - deploy

#build-nuxt-app:
#  stage: build
#  script:
#    - npm install -g pnpm
#    - pnpm install
#    - pnpm run build

dockerize-app:
  stage: dockerize
  only:
  - main
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker build -t $IMAGE_TAG -t $IMAGE_TAG_LATEST .
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_PRIVATE_REGISTRY
    - docker push $BASE_IMAGE_TAG --all-tags

deploy-app-in-remote-host:
  stage: deploy
  only:
  - main
  image: alpine:3.18
  before_script:
    - apk add --no-cache openssh sshpass
  script:
    - sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no docker-compose.yaml "$SSH_USER@$SSH_HOST":docker-compose.yaml
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" 
      "docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_PRIVATE_REGISTRY &&
      docker compose pull &&
      docker compose up --force-recreate --build -d"


```

This is the gitlab runner docker container (part of docker compose):
```yaml
  gitlab-runner-1:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner-1
    restart: unless-stopped
    depends_on:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker-volumes/gitlab/gitlab-runner:/etc/gitlab-runner
    networks:
      - internal-services-network

```

Full gitlab runner log:
```
[0KRunning with gitlab-runner 15.11.0 (436955cb)[0;m
[0K  on Docker In Docker Runner 1 sARm_8Aj, system ID: r_yBMthZMbemYS[0;m
section_start:1719271948:prepare_executor
[0K[0K[36;1mPreparing the "docker" executor[0;m[0;m
[0KUsing Docker executor with image docker:20.10.16 ...[0;m
[0KStarting service docker:20.10.16-dind ...[0;m
[0KPulling docker image docker:20.10.16-dind ...[0;m
[0KUsing docker image sha256:1f6c0346b90562fa44a32011666df7a7f413ee260a0510b52ca974bef4d50f15 for docker:20.10.16-dind with digest docker@sha256:56ef400f08be1ca817d7e2cfdb43803786ab28d84c8167e8590622d9bab5b415 ...[0;m
[0KWaiting for services to be up and running (timeout 30 seconds)...[0;m
[0KPulling docker image docker:20.10.16 ...[0;m
[0KUsing docker image sha256:2a153cb5c7c52610ceb46876231f1c7ab8d2a0926aaeb5283994ef3d6f78def9 for docker:20.10.16 with digest docker@sha256:5bc07a93c9b28e57a58d57fbcf437d1551ff80ae33b4274fb60a1ade2d6c9da4 ...[0;m
section_end:1719271955:prepare_executor
[0Ksection_start:1719271955:prepare_script
[0K[0K[36;1mPreparing environment[0;m[0;m
Running on runner-sarm8aj-project-36-concurrent-0 via c3b9dbc68895...
section_end:1719271955:prepare_script
[0Ksection_start:1719271955:get_sources
[0K[0K[36;1mGetting source from Git repository[0;m[0;m
[32;1mFetching changes with git depth set to 20...[0;m
Reinitialized existing Git repository in /builds/felipe/felipesanchezweb-nuxt/.git/
[32;1mChecking out 04a0e108 as detached HEAD (ref is main)...[0;m

[32;1mSkipping Git submodules setup[0;m
section_end:1719271956:get_sources
[0Ksection_start:1719271956:step_script
[0K[0K[36;1mExecuting "step_script" stage of the job script[0;m[0;m
[0KUsing docker image sha256:2a153cb5c7c52610ceb46876231f1c7ab8d2a0926aaeb5283994ef3d6f78def9 for docker:20.10.16 with digest docker@sha256:5bc07a93c9b28e57a58d57fbcf437d1551ff80ae33b4274fb60a1ade2d6c9da4 ...[0;m
[32;1m$ docker build -t $IMAGE_TAG -t $IMAGE_TAG_LATEST .[0;m
Sending build context to Docker daemon  3.502MB

Step 1/11 : FROM oven/bun:1-alpine as build
1-alpine: Pulling from oven/bun
73baa7ef167e: Pulling fs layer
68b63ceff7e6: Pulling fs layer
63c40d857c27: Pulling fs layer
0a40c52bbc64: Pulling fs layer
476abd678aa7: Pulling fs layer
0a40c52bbc64: Waiting
476abd678aa7: Waiting
63c40d857c27: Verifying Checksum
63c40d857c27: Download complete
73baa7ef167e: Download complete
73baa7ef167e: Pull complete
476abd678aa7: Verifying Checksum
476abd678aa7: Download complete
0a40c52bbc64: Download complete
68b63ceff7e6: Verifying Checksum
68b63ceff7e6: Download complete
68b63ceff7e6: Pull complete
63c40d857c27: Pull complete
0a40c52bbc64: Pull complete
476abd678aa7: Pull complete
Digest: sha256:aa2fe66811bef1b9a4062479e9918fcdf79921c0bb8921ca21e918c80aebe8fb
Status: Downloaded newer image for oven/bun:1-alpine
 ---> 2b1bca15eb9e
Step 2/11 : WORKDIR /app
 ---> Running in b860bb36e495
Removing intermediate container b860bb36e495
 ---> 6f48c74a7fc5
Step 3/11 : COPY . /app
 ---> 7be47ccc1a91
Step 4/11 : RUN bun install
 ---> Running in dffbe8d40289
[91mbun install v1.1.16 (bf7b327f)
[0m[91mResolving dependencies
[0m[91mResolved, downloaded and extracted [4816]
[0m[91mSaved lockfile

[0m[91m$ nuxt prepare
[0m[91m============================================================
Bun v1.1.16 (bf7b327f) Linux x64 (baseline)
Args: "node" "/app/node_modules/.bin/nuxt" "prepare"
Features: jsc Bun.stdin(2) tsconfig 
Builtins: "bun:jsc" "bun:main" "node:assert" "node:buffer" "node:crypto" "node:fs" "node:module" "node:os" "node:path" "node:perf_hooks" "node:process" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:v8" 
Elapsed: 15576ms | User: 10861ms | Sys: 4735ms
RSS: [0m[91m13.78GB | Peak: 8.14GB | Commit: 13.78GB | Faults: 0

panic(main thread): Segmentation fault at address 0x4EC6E000000
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.16/Bn1bf7b327AqggggE216ymE+xxQuo56lDu7z+gDy7jtlD2/m8/D__6t/98D6t/98DA24uCggggguD

[0m[91merror: postinstall script from "felipesanchezweb-nuxt" terminated by SIGILL (Illegal instruction)
============================================================
Bun v1.1.16 (bf7b327f) Linux x64 (baseline)
Args: "bun" "install"
Features: extracted_packages(1243) lifecycle_scripts spawn 
Elapsed: 29061ms | User: 2872ms | Sys: 3655ms
RSS: [0m[91m0.02ZB | Peak: 0.58GB | Commit: 0.02ZB | Faults: 0

panic(main thread): Segmentation fault at address 0x0
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.16/Bi1bf7b327AgghkI+xxQ46l6+C2rj1mD8so6+Ck5ymhD072k/Dimsh7C+hz57C+98i8Cg8wz3CA2AA

[0mThe command '/bin/sh -c bun install' returned a non-zero code: 132
section_end:1719271991:step_script
[0Ksection_start:1719271991:cleanup_file_variables
[0K[0K[36;1mCleaning up project directory and file based variables[0;m[0;m
section_end:1719271991:cleanup_file_variables
[0K[31;1mERROR: Job failed: exit code 132
[0;m
```

### Stack Trace (bun.report)

Bun v1.1.16 ([`bf7b327`](<https://github.com/oven-sh/bun/tree/bf7b327f68568104a5e40c1944b7b255b02f0745>)) on linux x86_64_baseline [RunAsNodeCommand]

Segmentation fault at address 0x4EC6E000000

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/ld-temp.o#L0>): `WTF::jscSignalHandler`
- `??`
- [`encoding.zig:905`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/bun.js/webcore/encoding.zig#L905>): `src.string.SliceWithUnderlyingString.transcodeFromOwnedSlice`
- [`node_fs.zig:5489`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/bun.js/node/node_fs.zig#L5489>): `src.bun.js.node.node_fs.NodeFS.readFile__anon_93371`
- [`node_fs_binding.zig:64`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/bun.js/node/node_fs_binding.zig#L64>): `NodeJSFSPrototype__readFileSync`
- [`ZigGeneratedClasses.cpp:27628`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745//build/bun/build/codegen/ZigGeneratedClasses.cpp#L27628>): `WebCore::NodeJSFSPrototype__readFileSyncCallback`
- *2 unknown/js code*
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/ld-temp.o#L0>): `llint_op_call`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/ld-temp.o#L0>): `llint_op_call`
