### ISSUE TITLE
`bun install --frozen-lockfile` in workspaces works locally but fails when building docker image

### ISSUE THREAD

**Issue by cybercoder-naj** [oven-sh/bun#12252]
### What version of Bun is running?

1.1.13+bd6a60512

### What platform is your computer?

Linux 6.6.32-1-lts x86_64 unknown

### What steps can reproduce the bug?

1. Initialise a bun repo `bun init`
2. Delete `node_modules`, `bun.lockb` and `index.ts`.
3. Add `"workspaces": ["server"]` in `package.json`.
4. Create an example server, I used `bun create hono server`.
  a. In the installation process, do not install dependencies.
5. In the root directory of the monorepo setup, run `bun install`.
6. Create a `Dockerfile` of the following:

```dockerfile
FROM oven/bun:1.1.13
WORKDIR /app
COPY package.json bun.lockb server/package.json ./
RUN bun install --frozen-lockfile
COPY . .
CMD ["bun", "run", "dev"]
```

### What is the expected behavior?

When I delete `node_modules` from the root directory of the project, `bun install --frozen-lockfile` succeeds without any error.
However, when I build the docker image, the resultant error is, 
```bash
bun install v1.1.13 (bd6a6051)
Resolving dependencies
Resolved, downloaded and extracted [2]
error: lockfile had changes, but lockfile is frozen
note: try re-running without --frozen-lockfile and commit the updated lockfile
```

### What do you see instead?

Running it locally:
![image](https://github.com/oven-sh/bun/assets/48282810/8dd9ae6a-0cbe-4253-8e82-0406a446c4c7)

But when building a docker image:
![2024-06-29_22-07](https://github.com/oven-sh/bun/assets/48282810/3ee87c44-bd26-46f0-a13a-0efbf7374973)

### Additional information

When building a docker image in a single project, it works. The issue is with bun workspaces.

**Comment by Jarred-Sumner** [comment]
Does this reproduce on Bun v1.1.17? The bun.lockb file is checked in to version control and copied to the Docker image right?

**Comment by cybercoder-naj** [comment]
Yes, in my monorepo setup, updating bun to 1.1.17 locally and changing the version of the docker image does not fix the issue.

**Comment by cybercoder-naj** [comment]
Any resolutions to this thread?

**Comment by bjon** [comment]
@cybercoder-naj I had to copy my "packages" as well.

`COPY packages packages`

ps. I guess it fails cause bun doesn't find any packages, in the workspace.

**Comment by cybercoder-naj** [comment]
Unfortunately, that did not solve the issue.. Inside of a docker environment, bun complains about the lock file being modified.

**Comment by bjon** [comment]
Hmmm strange. It works for me in Bun 1.1.18

**Comment by bjon** [comment]
And I got this in my package.json.

```json
{
  "workspaces": ["packages/*"]
}
```

**Comment by cybercoder-naj** [comment]
Here is my [reproduction repo](https://github.com/cybercoder-naj/bun-monorepo-docker). Can you clone this and type two commands?

```bash
# First one
bun install --production

# Second one
docker build . --tag bun-issue:1.0.0
```

Is this an issue only on my system? Doesn't that defeat the entire purpose of docker?

**Comment by cybercoder-naj** [comment]
> Hmmm strange. It works for me in Bun 1.1.18

@bjon same issue with 1.1.18 :(

**Comment by cybercoder-naj** [comment]
> Running into the same issue with `bun@1.1.29`. What was the solution @cybercoder-naj?

Rookie mistake: I was incorrectly copying the directory structure into the image during build.

**Comment by gordinmitya** [comment]
Explanation for anyone who finds themselves here.
You need to copy all package.json files into the build container and place them in the correct directories. So:

```Dockerfile
# Wrong
COPY package.json bun.lock ./
# Also wrong
COPY package.json bun.lock ./
COPY packages/backend/package.json packages/frontend/package.json ./

RUN bun install --frozen-lockfile
```

```Dockerfile
# Correct
COPY packages/backend/package.json ./packages/backend/
COPY packages/frontend/package.json ./packages/frontend/
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile
```

**Comment by dominictobias** [comment]
Would prefer if I didn't have to install the frontend deps since I don't care about that in docket but seems in a monorepo I do (with a lockfile), oh well

**Comment by IslamZaoui** [comment]
This issue happened to me randomly after uninstalling a dependency from `apps/api` and when I deleted `packages/logger` folder

I'm using turborepo with bun workspaces:

`/compose.yaml`
```yaml
services:
    nginx:
        container_name: nginx
        restart: always
        build:
            context: .
            dockerfile: ./apps/nginx/Dockerfile
        ports:
            - 48273:48273
        networks:
            - app_network
        depends_on:
            - web

    web:
        container_name: web
        restart: always
        build:
            context: .
            dockerfile: ./apps/web/Dockerfile
        expose:
            - 5173
        networks:
            - app_network
        depends_on:
            - api

    api:
        container_name: api
        restart: always
        build:
            context: .
            dockerfile: ./apps/api/Dockerfile
        expose:
            - 3000
        networks:
            - app_network

networks:
    app_network:
```
`/apps/api/Dockerfile`
```dockerfile
FROM oven/bun:alpine AS base
WORKDIR /app

FROM base AS builder
RUN bun add -g turbo
COPY . .
RUN turbo prune web --docker

FROM base AS install
RUN mkdir -p /temp/dev
COPY --from=builder /app/out/json /temp/dev/
RUN cd /temp/dev && bun install --frozen-lockfile

RUN mkdir -p /temp/prod
COPY --from=builder /app/out/json /temp/prod/
RUN cd /temp/prod && bun install --frozen-lockfile --production


FROM base AS prerelease
COPY --from=install /temp/dev/node_modules node_modules
COPY --from=builder /app/out/full/ .
COPY --from=builder /app/out/bun.lock .
RUN bun turbo build --filter=web...

FROM base AS release
COPY --from=install /temp/prod/node_modules node_modules
COPY --from=prerelease /app/apps/web/build ./build

USER bun
ENV PORT=5173
EXPOSE 5173/tcp
CMD bun --bun build/index.js
```

I found a work around to ignore the lock file changes by removing `--frozen-lockfile` and replacing `--production` with `--omit=dev`

now this should be working until we have a big day for bun workspaces and monorepos
