### ISSUE TITLE
Rust Panic Crash when Using Temporal

### ISSUE THREAD

**Issue by ccravens** [oven-sh/bun#12552]
### What version of Bun is running?

1.1.19+110849355

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

Temporal is an open source project that enables the development of resilient code (temporal.io). When trying to use Temporal in a new bun project I get the following panic crash. I do have a working version with NodeJS against a local Temporal dev instance:

```bash
thread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/neon-runtime-0.10.1/src/napi/bindings/functions.rs:360:43:
Failed to find N-API version: DlSym { desc: "dlsym(RTLD_DEFAULT, napi_get_version): symbol not found" }
stack backtrace:
   0:        0x1215873dc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h01b2beffade888b2
   1:        0x1211beef8 - core::fmt::write::hbadb443a71b75f23
   2:        0x121562630 - std::io::Write::write_fmt::hc09d7755e3ead5f0
   3:        0x121588af8 - std::sys_common::backtrace::print::h28349e5c25acbac7
   4:        0x1215882a8 - std::panicking::default_hook::{{closure}}::hd24b6196784d991e
   5:        0x121589d80 - std::panicking::rust_panic_with_hook::h84760468187ddc85
   6:        0x121588ddc - std::panicking::begin_panic_handler::{{closure}}::he666a5eb600a7203
   7:        0x121588d40 - std::sys_common::backtrace::__rust_end_short_backtrace::h592f44d2bf9f843f
   8:        0x121588d34 - _rust_begin_unwind
   9:        0x121a735ec - core::panicking::panic_fmt::h98bbf7bdf4994454
  10:        0x121a73898 - core::result::unwrap_failed::h8e3b933261dd7fec
  11:        0x12125766c - neon_runtime::napi::bindings::functions::load::h569991dbf4b862ee
  12:        0x12125c5e8 - std::sync::once::Once::call_once::{{closure}}::h05dfe72429f364cd
  13:        0x121a8fe14 - std::sys::sync::once::queue::Once::call::hfdfe59dd23f24861
  14:        0x1219061ac - _napi_register_module_v1
fatal runtime error: failed to initiate panic, error 5
```

Steps to reproduce:
- Start a Temporal instance:

```yaml
version: '3.7'
services:

  opensearch:
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms256m -Xmx256m
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=512mb
      - cluster.routing.allocation.disk.watermark.high=256mb
      - cluster.routing.allocation.disk.watermark.flood_stage=128mb
      - plugins.security.disabled=true
    image: opensearchproject/opensearch:2.5.0
    ulimits:
      #      memlock:
      #        soft: -1 # Set memlock to unlimited (no soft or hard limit)
      #        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    expose:
      - 9200
    volumes:
      - ./data/opensearch:/usr/share/opensearch/data

  postgresql:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      PGDATA: /var/lib/postgresql/data/db_data
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/db_data
    shm_size: '1024m'

  temporal:
    image: temporalio/auto-setup:1.24.2
    ports:
      - 7233:7233
    depends_on:
      - postgresql
      - opensearch
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/config/dynamicconfig/development-sql.yaml
      - ENABLE_ES=true
      - ES_SEEDS=opensearch
      - ES_VERSION=v7
    volumes:
      - ./typescript/api/temporal:/etc/temporal/config/dynamicconfig
    labels:
      kompose.volume.type: configMap

  temporal-admin-tools:
    image: temporalio/admin-tools:1.24
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    stdin_open: true
    tty: true

  temporal-ui:
    image: temporalio/ui:2.28.0
    ports:
      - 8888:8080
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
```

`development-cass.yaml`
```yaml
system.forceSearchAttributesCacheRefreshOnRead:
  - value: true # Dev setup only. Please don't turn this on in production.
    constraints: {}
```

`development-sql.yaml`
```yaml
limit.maxIDLength:
  - value: 255
    constraints: {}
system.forceSearchAttributesCacheRefreshOnRead:
  - value: true # Dev setup only. Please don't turn this on in production.
    constraints: {}
```

- Init a new bun project
`bun init -y`

- tsconfig.json
```json
{
  "compilerOptions": {
    // Enable latest features
    "lib": ["ESNext"],
    "target": "ESNext",
    "module": "ESNext",
    "moduleDetection": "force",
    "jsx": "react-jsx",
    "allowJs": true,

    // Bundler mode
    "moduleResolution": "node",
    "allowImportingTsExtensions": true,
    "verbatimModuleSyntax": true,
    "noEmit": true,

    // Best practices
    "strict": true,
    "skipLibCheck": true,
    "noFallthroughCasesInSwitch": true,

    // Some stricter flags (disabled by default)
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noPropertyAccessFromIndexSignature": false
  }
}
```

- package.json
```json
{
  "name": "tmp",
  "module": "index.ts",
  "type": "module",
  "devDependencies": {
    "@types/bun": "latest"
  },
  "peerDependencies": {
    "typescript": "^5.0.0",
    "@temporalio/activity": "1.10.1",
    "@temporalio/client": "1.10.1",
    "@temporalio/worker": "1.10.1",
    "@temporalio/workflow": "1.10.1"
  }
}
```

- index.ts
```typescript
import { NativeConnection, Worker } from '@temporalio/worker';
import * as activities from './temporal/activities';

await Worker.create({
    connection: await NativeConnection.connect({
        address: `${process.env.TEMPORAL_HOST}:${process.env.TEMPORAL_PORT}`,
    }),
    namespace: 'default',
    taskQueue: 'tasks',
    identity: 'test',
    workflowsPath: require.resolve('./temporal/workflows'),
    activities,
});
```

- Created empty index.ts files at
`temporal/activities/index.ts` and `temporal/workflows/index.ts`

### What is the expected behavior?

I would expect Temporal worker to connect to the temporal service.

### What do you see instead?

Instead I get the following rust stack trace:

```bash
thread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/neon-runtime-0.10.1/src/napi/bindings/functions.rs:360:43:
Failed to find N-API version: DlSym { desc: "dlsym(RTLD_DEFAULT, napi_get_version): symbol not found" }
stack backtrace:
   0:        0x1215873dc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h01b2beffade888b2
   1:        0x1211beef8 - core::fmt::write::hbadb443a71b75f23
   2:        0x121562630 - std::io::Write::write_fmt::hc09d7755e3ead5f0
   3:        0x121588af8 - std::sys_common::backtrace::print::h28349e5c25acbac7
   4:        0x1215882a8 - std::panicking::default_hook::{{closure}}::hd24b6196784d991e
   5:        0x121589d80 - std::panicking::rust_panic_with_hook::h84760468187ddc85
   6:        0x121588ddc - std::panicking::begin_panic_handler::{{closure}}::he666a5eb600a7203
   7:        0x121588d40 - std::sys_common::backtrace::__rust_end_short_backtrace::h592f44d2bf9f843f
   8:        0x121588d34 - _rust_begin_unwind
   9:        0x121a735ec - core::panicking::panic_fmt::h98bbf7bdf4994454
  10:        0x121a73898 - core::result::unwrap_failed::h8e3b933261dd7fec
  11:        0x12125766c - neon_runtime::napi::bindings::functions::load::h569991dbf4b862ee
  12:        0x12125c5e8 - std::sync::once::Once::call_once::{{closure}}::h05dfe72429f364cd
  13:        0x121a8fe14 - std::sys::sync::once::queue::Once::call::hfdfe59dd23f24861
  14:        0x1219061ac - _napi_register_module_v1
fatal runtime error: failed to initiate panic, error 5
```
