### ISSUE TITLE
Bun Memory Leak when `fetch` used with `proxy`

### ISSUE THREAD

**Issue by Zamion101** [oven-sh/bun#12846]
### What version of Bun is running?

1.1.20+ae1948925

### What platform is your computer?

Linux 5.15.153.1-microsoft-standard-WSL2 x86_64 unknown

### What steps can reproduce the bug?

Here is a Reproduction of the bug in simple steps with useful informations.

```ts
const USER_AGENT = 'Mozilla/5.0 (Linux; Android 9; SAMSUNG SM-G975F Build/PPR1.180610.011) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/9.4 Chrome/67.0.3396.87 Mobile Safari/537.36'
const PROXY_URL = '<HTTP_PROXY_URL>'

export async function proxyRequest(url: string) {

  const options = {
      proxy: PROXY_URL
  }
  const headers: Record<string, string> = {}
  headers['user-agent'] = USER_AGENT
  headers['accept'] = 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7'
  headers['accept-language'] = 'tr-TR,tr;q=0.9,en-US;q=0.8,en;q=0.7'
  headers['cache-control'] = 'no-cache'
  headers['pragma'] = 'no-cache'

  return await fetch(url, {
    method: 'GET',
    headers: headers,
    // proxy: options.proxy, // Comment out to see expected behavior
    keepalive: false,
  })

}

let requestMade = 0
let peakMemoryUsage = 0
const startMemory = (process.memoryUsage.rss() / 1024 / 1024) | 0
for (let a = 0; a < 10; a++) {
  const startIteration = (process.memoryUsage.rss() / 1024 / 1024) | 0
  const requestCountStart = requestMade
  for (let b = 0; b < 10; b++) {
    //542KB https://media.4-paws.org/5/b/8/b/5b8bca3f74342210ccca652c651f2d7e23288753/VIER%20PFOTEN_2019-12-13_209-2890x2000.jpg
    //1.2MB https://images.pexels.com/photos/774731/pexels-photo-774731.jpeg?cs=srgb&dl=pexels-kerber-774731.jpg&fm=jpg
    let beforeRequest = (process.memoryUsage.rss() / 1024 / 1024) | 0
    const response = await proxyRequest(`https://images.pexels.com/photos/774731/pexels-photo-774731.jpeg?cs=srgb&dl=pexels-kerber-774731.jpg&fm=jpg`)
    requestMade++
    let afterRequest = (process.memoryUsage.rss() / 1024 / 1024) | 0
    Bun.gc(true);
    let afterGC = (process.memoryUsage.rss() / 1024 / 1024) | 0

    if (afterGC > peakMemoryUsage) peakMemoryUsage = afterGC

    console.log(`#${requestMade - 1} - beforeRequest: ${beforeRequest} -> afterRequest: ${afterRequest} -> afterGC: ${afterGC}`)
  }
  const endIteration = (process.memoryUsage.rss() / 1024 / 1024) | 0
  console.log(`\n\nEnd of iteration #${a}:\n\tMemory Used (RES): ${(endIteration)}MB\n\tHeap Growth This Iteration: ${(endIteration - startIteration)} MB\n\tPer Request Growth: ${(endIteration - startIteration) / (requestMade - requestCountStart)} MB\n\n`)

  // console.log(require('bun:jsc').heapStats())
}
let endMemory = (process.memoryUsage.rss() / 1024 / 1024) | 0
console.log(`[Overall Stats]\n\tTotal Requests: ${requestMade}\n\tPer Request Growth: ${(endMemory - startMemory) / requestMade} MB\n\tPeak Memory Usage: ${peakMemoryUsage} MB`)
console.log(`\nSleeping for Automatic GC to kick in...\n`)
await new Promise((resolve) => setTimeout(resolve, 10 * 1000));
endMemory = (process.memoryUsage.rss() / 1024 / 1024) | 0
console.log(`[After Sleep Stats]\n\tStart Memory Usage: ${startMemory} MB\n\tEnd Memory Usage: ${endMemory} MB\n\tHeap Growth: ${(endMemory - startMemory)} MB`)

```

### What is the expected behavior?

It's expected that Bun will manage Memory efficiently and release memory when the scope is destroyed. Also the reproduction code should show a result something like this

with `--smoll`
```yaml
<...>
End of iteration #9:
        Memory Used (RES): 68MB
        Heap Growth This Iteration: -1 MB
        Per Request Growth: -0.1 MB


[Overall Stats]
        Total Requests: 100
        Per Request Growth: 0.19 MB
        Peak Memory Usage: 70 MB

Sleeping for Automatic GC to kick in...

[After Sleep Stats]
        Start Memory Usage: 49 MB
        End Memory Usage: 69 MB
        Heap Growth: 20 MB
```
without `--smoll`
```yaml
<...>
End of iteration #9:
        Memory Used (RES): 76MB
        Heap Growth This Iteration: 3 MB
        Per Request Growth: 0.3 MB


[Overall Stats]
        Total Requests: 100
        Per Request Growth: 0.23 MB
        Peak Memory Usage: 78 MB

Sleeping for Automatic GC to kick in...

[After Sleep Stats]
        Start Memory Usage: 53 MB
        End Memory Usage: 74 MB
        Heap Growth: 21 MB
```
### What do you see instead?

Bun does not release Memory back and keep accumulating Memory even after the scope has been destroyed. Which leads to permanent allocation of memory and it's leak. Also the result of the reproduction code is

with `--smoll`
```yaml
<...>
End of iteration #9:
        Memory Used (RES): 157MB
        Heap Growth This Iteration: 10 MB
        Per Request Growth: 1 MB


[Overall Stats]
        Total Requests: 100
        Per Request Growth: 1.04 MB
        Peak Memory Usage: 157 MB

Sleeping for Automatic GC to kick in...

[After Sleep Stats]
        Start Memory Usage: 53 MB
        End Memory Usage: 152 MB
        Heap Growth: 99 MB
```

without `--smoll`
```yaml
<...>
End of iteration #9:
        Memory Used (RES): 148MB
        Heap Growth This Iteration: 11 MB
        Per Request Growth: 1.1 MB


[Overall Stats]
        Total Requests: 100
        Per Request Growth: 0.99 MB
        Peak Memory Usage: 148 MB

Sleeping for Automatic GC to kick in...

[After Sleep Stats]
        Start Memory Usage: 49 MB
        End Memory Usage: 148 MB
        Heap Growth: 99 MB
```
