### ISSUE TITLE
Error using custom npm registry in bunfig.toml

### ISSUE THREAD

**Issue by HexSleeves** [oven-sh/bun#140]
Using bunfig.toml to set a custom npm registry leads to an error.

```toml
[install.scopes]
"@mybigcompany" = { token = "123456", url = "https://registry.mybigcompany.com" }
```

Error produced by running `bun install`:

<img width="695" alt="CleanShot 2022-04-10 at 18 16 48@2x" src="https://user-images.githubusercontent.com/9278174/162644112-5e194234-da0e-4115-824c-bd623a2c5d7e.png">

This is using the example to blur out my custom scope and token, but the same results happen with valid url and token entities

**Comment by Jarred-Sumner** [comment]
This is a TOML parsing bug.

As a temporary workaround, try:
```toml
[install.scopes."@mybigcompany"]
token = "123456"
url = "https://registry.mybigcompany.com"
```
