### ISSUE TITLE
Custom registry url gets trimmed if trailing forward slash is missing

### ISSUE THREAD

**Issue by luciodale** [oven-sh/bun#14017]
### What version of Bun is running?

1.1.26

### What platform is your computer?

x64

### What steps can reproduce the bug?

Add under `~/` dir a .bunfig.toml file like this: 
```toml
[install]
registry = { url = "https://www.my-repo/npm-enterprise", token = "..."}
```
 Then:
 
`bun install`

### What is the expected behavior?

When running `bun install`, I should see the url used to fetch the libs (react for example) as: `https://www.my-repo/npm-enterprise/react`

### What do you see instead?

I see the url to fetch react as: `https://www.my-repo/react`

### Additional information

Adding a trailing forward slash to the url fixes the problem i.e. `https://www.my-repo/npm-enterprise/`. Though, I don't think it should be required, as `https://www.my-repo/npm-enterprise` is a perfectly valid url.

**Comment by Zooce** [comment]
I'm seeing this as well, but I noticed it with `bun outdated` which printed no output:

```bash
$ bun oudated
bun outdated v1.1.28 (cf4e9cb6)

$
```

**Comment by Zooce** [comment]
This seems to be broken again. Even with a trailing slash, I'm getting 404s.

```toml
# .bunfig.toml
[install]
registry = "https://my.registry.com/npm/"
```

```bash
$ bun install
bun install v1.1.34 (5e5e7c60)
error: GET https://my.registry.com/@some-scope%2fsome-package - 404
error: @some-scope/some-package@^3.2.0 failed to resolve
```

```bash
$ bun update -g
bun install v1.1.34 (5e5e7c60)
error: GET https://my.registry.com/typescript - 400
error: typescript@^5.6.2 failed to resolve
```
