### ISSUE TITLE
Bun exists with 'Killed'

### ISSUE THREAD

**Issue by GerbenRampaart** [oven-sh/bun#14179]
### What version of Bun is running?

1.1.29+6d43b3662

### What platform is your computer?

linux / kubernetes

### What steps can reproduce the bug?

I hope you can make heads or tails of this one, I'm supplying as much as I know.

When I containerise an app with bun (latest oven/bun:alpine) with these resources (helm chart):
```
resources:
  requests:
    cpu: 100m
    memory: 80Mi
  limits:
    cpu: 250m
    memory: 100Mi
```

and I deploy it to kubernetes, kubernetes can't start the pod because it exits with 'Killed' without logging anything.

The app is a single javascript file of about 19MB (it's a bundle with things like express, nestjs and so on).

However when I up the resources to this, it works fine:
```
resources:
  requests:
    cpu: 200m
    memory: 160Mi
  limits:
    cpu: 500m
    memory: 200Mi
```

Note that I can pull the container locally then it also works fine, so the problem seems to be resource constraints.

I don't have any other error message or logging other than 'Killed'. I tried running it with --smol but that made no difference.

Thanks for taking a look at this.

### Additional information

Note that the resources I originally set are the resources I tend to use for node apps, which seem to work fine with those.
