### ISSUE TITLE
`Bun.build` with `experimentalCss` doesn't work with nested CSS

### ISSUE THREAD

**Issue by noClaps** [oven-sh/bun#14420]
### What version of Bun is running?

1.1.30+7996d06b8

### What platform is your computer?

Darwin 24.0.0 arm64 arm

### What steps can reproduce the bug?

If you have a CSS file like:

```css
/* style.css */
body {
	font-family: ui-sans-serif, sans-serif;
	background-color: black;
	display: grid;
	width: 100dvw;
	height: 100dvh;
	margin: 0;
	place-items: center;
}

h1 {
	color: white;
}
```

then it builds correctly. However, if the CSS is nested, like:

```css
/* style-breaking.css */
body {
	font-family: ui-sans-serif, sans-serif;
	background-color: black;
	display: grid;
	width: 100dvw;
	height: 100dvh;
	margin: 0;
	place-items: center;

	h1 {
		color: white;
	}
}
```

then the bundler breaks.

Here's the bundler code I am using:

```ts
Bun.build({
	entrypoints: ["style.css"], // This one works fine
	outdir: "dist",
	experimentalCss: true,
});

Bun.build({
	entrypoints: ["style-breaking.css"], // This one breaks
	outdir: "dist",
	experimentalCss: true,
});
```

### What is the expected behavior?

Both CSS files should be built correctly. CSS nesting has been [supported in all major browsers](https://caniuse.com/css-nesting) for some time now.

### What do you see instead?

The breaking stylesheet fails to build, and I get an error in my console:

```
zsh: illegal hardware instruction  bun run build.ts
```

and with the CLI:

```
zsh: illegal hardware instruction  bun build --experimental-css style-breaking.css --outdir dist
```
