### ISSUE TITLE
Bundle CSS hexadecimal content property add redundant "\\" character to output

### ISSUE THREAD

**Issue by binhtddev** [oven-sh/bun#15168]
### What version of Bun is running?

1.1.34+5e5e7c60f

### What platform is your computer?

Linux 5.15.153.1-microsoft-standard-WSL2 x86_64 unknown

### What steps can reproduce the bug?

Given I have 2 files:
```ts
// test.ts
await Bun.build({
  entrypoints: ["./test.css"],
  outdir: "test",
  experimentalCss: true,
});
```
```css
/* test.css */
.special::before {
  content: '\20'
}
```

When I run `bun test.ts`

### What is the expected behavior?

Then I should receive this output:
```css
/* test.css */
.special:before {
  content: " ";
}
```

### What do you see instead?

But I received this output:
```css
/* test.css */
.special:before {
  content: " \\";
}
```
