### ISSUE TITLE
Running bun amd64 in docker under platform rosetta2 translation breaks Bun.serve

### ISSUE THREAD

**Issue by lil5** [oven-sh/bun#15204]
### What version of Bun is running?

1.1.34+5e5e7c60f

### What platform is your computer?

Darwin 24.1.0 arm64 arm

### What steps can reproduce the bug?

1. create a bun project and add the following to index.ts

command: `bun init; bun i`

file: `index.ts`
```ts
Bun.serve({
  fetch(req) {
    return new Response("Bun!");
  },
});
```
2. create a docker file 

file: `Dockerfile`
```dockerfile
FROM oven/bun AS base
WORKDIR /app

COPY bun.lockb . 
COPY package.json . 

# Install dependencies
RUN bun install --frozen-lockfile

COPY . . 

EXPOSE 3000/tcp
ENTRYPOINT [ "bun", "run", "./index.ts" ]
```

file: `.dockerignore`
```
/node_modules
```

3. create a docker-compose file
file: `docker-compose.yml`
```yml
services:
  app:
    platform: linux/amd64
    build:
      context: .
    ports:
      - 127.0.0.1:3000:3000
    restart: unless-stopped
    environment:
      - PORT=3000
```

4. Build and run `docker compose up -d --build`
5. Create a request to bun `wget --spider http://localhost:3000/`, run this multiple times and it will stop working after a short while.

### What is the expected behavior?

200 responses returning the text "Bun!"

### What do you see instead?

Request without a response, endlessly stuck with no response, no console errors.

### Additional information

Running on M2 15.1 (24B83) with Docker Desktop 4.35.1 (173168)
