### ISSUE TITLE
CSS build with sourcemap produces invalid 'JS style' sourcemap link comments

### ISSUE THREAD

**Issue by maxmilton** [oven-sh/bun#15532]
### What version of Bun is running?

1.1.39-canary.8+d2acb2eac

### What platform is your computer?

Linux 6.12.1-2-cachyos x86_64 unknown

### What steps can reproduce the bug?

1. Create files:

`build.ts`:

```ts
await Bun.build({
  entrypoints: ['test.css'],
  outdir: 'dist',
  experimentalCss: true,
  sourcemap: 'linked',
});
```

`test.css`:

```css
body {
  color: red;
}
```

2. Run: `bun build.ts`

### What is the expected behavior?

Bun injects sourcemap link as a valid CSS comment.

`dist/test.css`:

```css
/* test.css */
body {
  color: red;
}

/*# sourceMappingURL=test.css.map */

```

### What do you see instead?

Bun injects a JS style sourcemap link and debugId.

`dist/test.css`:

```css
/* test.css */
body {
  color: red;
}

//# debugId=ECAEAE065D05B5AF64756E2164756E21
//# sourceMappingURL=test.css.map

```

Occurs for both CSS as the entrypoint or as an imported file.
