### ISSUE TITLE
Bun bundler incorrectly merges distinct CSS classes

### ISSUE THREAD

**Issue by lleqsnoom** [oven-sh/bun#15979]
### What version of Bun is running?

1.1.42+50eec0025

### What platform is your computer?

Linux 6.10.14-linuxkit aarch64 unknown

### What steps can reproduce the bug?

**Description:**
When bundling CSS files using Bun, distinct classes with different `flex-direction` properties are incorrectly merged, resulting in unintended styling.

**Steps to Reproduce:**
1. Create a CSS file with the following content:
```css
.flex-row-reverse {
    flex-direction: row-reverse;
}
.flex-col {
    flex-direction: column;
}
```

### What is the expected behavior?

```css
.flex-row-reverse {
    flex-direction: row-reverse;
}
.flex-col {
    flex-direction: column;
}
```

### What do you see instead?

```css
.flex-row-reverse, .flex-col {
    flex-direction: row-reverse;
}
```
