### ISSUE TITLE
Bun transforms hexadecimal escape sequences representing Unicode characters into their actual character equivalents

### ISSUE THREAD

**Issue by lleqsnoom** [oven-sh/bun#15980]
### What version of Bun is running?

1.1.42+50eec0025

### What platform is your computer?

Linux 6.10.14-linuxkit aarch64 unknown

### What steps can reproduce the bug?

When bundling CSS files, Bun transforms hexadecimal escape sequences representing Unicode characters into their actual character equivalents, followed by an extraneous backslash (\). This alteration can cause icons and special symbols to render incorrectly.

```css
.fa-shop-slash {
  --fa: "\e070";
  --fa--fa: "\e070\e070";
}

.fa-store-alt-slash {
  --fa: "\e070";
  --fa--fa: "\e070\e070";
}
```

### What is the expected behavior?

```css
.fa-shop-slash, .fa-store-alt-slash {
  --fa: "\e070";
  --fa--fa: "\e070\e070";
}
```

### What do you see instead?

```css
.fa-shop-slash, .fa-store-alt-slash {
  --fa: "\\";
  --fa--fa: "\\\\";
}
```
