### ISSUE TITLE
Bun build --experimental-html --experimental-css out of memory

### ISSUE THREAD

**Issue by qinyuhang** [oven-sh/bun#16408]
### How can we reproduce the crash?

simply run `bun build --experimental-html --experimental-css ./index.html --outdir=dist` 
```
bun build --experimental-html --experimental-css ./index.html --outdir=dist
============================================================
Bun v1.1.43 (76800b04) macOS Silicon
macOS v14.3
Args: "bun" "build" "--experimental-html" "--experimental-css" "./index.html" "--outdir=dist"
Features: tsconfig
Elapsed: 3ms | User: 3ms | Sys: 4ms
RSS: 14.89MB | Peak: 14.88MB | Commit: 1.07GB | Faults: 16

oh no: Bun has ran out of memory.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.43/Mb176800b0ABmvysSmwv2Omvm0FunrgB2y19J2t+nBuu87J__A9

[1]    73686 trace trap  bun build --experimental-html --experimental-css ./index.html --outdir=dist
```

### Relevant log output

```shell
bun build --experimental-html --experimental-css ./index.html --outdir=dist
============================================================
Bun v1.1.43 (76800b04) macOS Silicon
macOS v14.3
Args: "bun" "build" "--experimental-html" "--experimental-css" "./index.html" "--outdir=dist"
Features: tsconfig
Elapsed: 3ms | User: 3ms | Sys: 4ms
RSS: 14.89MB | Peak: 14.88MB | Commit: 1.07GB | Faults: 16

oh no: Bun has ran out of memory.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.43/Mb176800b0ABmvysSmwv2Omvm0FunrgB2y19J2t+nBuu87J__A9

[1]    73686 trace trap  bun build --experimental-html --experimental-css ./index.html --outdir=dist
```

### Stack Trace (bun.report)

Bun v1.1.43 ([`76800b0`](<https://github.com/oven-sh/bun/tree/76800b049a705b02f104089ba70d13b0667a4046>)) on macos aarch64 [BuildCommand]

Bun ran out of memory

- `src.css.declaration.DeclarationHandler.finalize`
- `src.css.declaration.DeclarationBlock.minify`
- `src.css.rules.rules.CssRuleList`
- `src.css.css_parser.StyleSheet`
- `src.bundler.bundle_v2.ParseTask.getAST`
- `src.bundler.bundle_v2.ParseTask.callback`
- `Thread.PosixThreadImpl.spawn__anon_127375.Instance.entryFn`

Features: tsconfig, tsconfig

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6220375221/">BUN-B8M</a></strong></sub>

**Comment by Jarred-Sumner** [comment]
Can you paste the CSS file? That would help @zackradisic reproduce and fix this

**Comment by qinyuhang** [comment]
Here is the css files

`index.css` (contains Chinese chars)
```css
.content {
  width: 1000px;
  margin: 0 auto;
}

.title {
  text-align: center;
  font-size: 30px;
  font-weight: 500;
  margin: 16px auto;
}

.code-container {
  color: #fff;
  background-color: #282c34; /* 深背景色 */
  border-radius: 8px; /* 圆角 */
  padding: 1em; /* 内边距 */
  margin: 0 auto;
  overflow-x: auto;
}

code {
  color: #f8f8f2; /* 浅色文字，增加对比 */
  font-family: 'Source Code Pro', monospace; /* 使用等宽字体 */
  font-size: 16px; /* 适当的字体大小 */
}

```

And `reset.css`
```css
html,
body {
  padding: 0;
  margin: 0;
  font-family: PingFang SC, Hiragino Sans GB, Microsoft YaHei, Arial, sans-serif;
}

p {
  margin: 0;
}

* {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  box-sizing: border-box;
}

.container-box {
  min-height: 100vh;
  max-width: 100%;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  padding-top: 10px;
}

main {
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}

.logo {
  width: 3.6rem;
  margin: 0 1.6rem;
}

.name {
  background: -webkit-linear-gradient(315deg, #788ec9 25%, #5978c0);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}

.description {
  text-align: center;
  line-height: 1.5;
  font-size: 1.3rem;
  color: #1b3a42;
  margin-bottom: 5rem;
}

.code {
  background: #fafafa;
  border-radius: 12px;
  padding: 0.6rem 0.9rem;
  font-size: 1.05rem;
  font-family: Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono,
    Bitstream Vera Sans Mono, Courier New, monospace;
}

.container-box .grid {
  display: grid;
  grid-template-columns: repeat(3, 33.33%);
  grid-row-gap: 20px;
  grid-column-gap: 20px;
  width: 1100px;
  margin-top: 3rem;
  align-items: center;
  justify-content: center;
}

.card {
  background: #f9f9f9;
  border: 1px solid transparent;
  transition: all.3s;
  padding: 2rem;
  border-radius: 2rem;
  display: flex;
  flex-direction: column;
  justify-content: center;
  color: inherit;
  text-decoration: none;
  transition: 0.15s ease;
}

.card-icon {
  display: flex;
  align-items: center;
  justify-content: center;
}

.card-icon-text {
  text-align: center;
  height: 3rem;
  font-size: 1.875rem;
  line-height: 2.25rem;
}

.card h2 {
  align-items: center;
  font-size: inherit;
  font-weight: 700;
  margin: 0;
  padding: 0;
  text-align: center;
}

.card p {
  font-size: 0.875rem;
  line-height: 1.25rem;
  font-weight: 500;
  padding-top: 0.5rem;
  color: rgba(60, 60, 60, 0.66);
}
```

And one css imported in the `App.tsx`
```typescript
import '@arco-design/web-react/dist/css/arco.css';
```
