### ISSUE TITLE
The bundler adds a backslash after each escape sequence in css strings.

### ISSUE THREAD

**Issue by afranchuk** [oven-sh/bun#16572]
### What version of Bun is running?

1.1.45+196621f25

### What platform is your computer?

Linux 6.12.9_1 x86_64 unknown

### What steps can reproduce the bug?

```css
/* repro.css */
.foo {
    content: "\2b";
}
```

Run `bun build --experimental-css repro.css`.

### What is the expected behavior?

Output should be
```css
/* repro.css */
.foo {
  content: "+";
}
```

### What do you see instead?

Output is
```css
/* repro.css */
.foo {
  content: "+\\";
}
```
