### ISSUE TITLE
css parsing is merging two unrelated flex class selectors in one

### ISSUE THREAD

**Issue by triptu** [oven-sh/bun#16596]
### What version of Bun is running?

1.2.0+b0c5a7655

### What platform is your computer?

Darwin 24.1.0 arm64 arm

### What steps can reproduce the bug?

This is regarding bundling with `index.html` file as entry point. Create a styles.css with below content which is linked in `index.html`.

```css
.flexrow {
	flex-direction: row;
}

.flexcol {
	flex-direction: column;
}

.hello {
	flex-wrap: wrap;
}

.world {
	flex-wrap: nowrap;
}
```

Run build - 

```sh
bun build ./index.html --outdir=dist
```

### What is the expected behavior?

The generated build file should have the same css as defined.

### What do you see instead?

The generated style file in the dist folder has the below content which is not correct.

```css
.flexrow, .flexcol {
  flex-direction: row;
}

.hello, .world {
  flex-wrap: wrap;
}
```
