### ISSUE TITLE
CSS rules improperly combined

### ISSUE THREAD

**Issue by afranchuk** [oven-sh/bun#16707]
### What version of Bun is running?

1.2.0+b0c5a7655

### What platform is your computer?

Linux 6.12.9_1 x86_64 unknown

### What steps can reproduce the bug?

```css
/* repro.css */
.flex-row {
	display: flex;
	flex-direction: row;
}

.flex-col {
	display: flex;
	flex-direction: column;
}
```

Run `bun build --experimental-css repro.css`.

### What is the expected behavior?

Output should be structurally unchanged from the input.

### What do you see instead?

The two classes are combined into one (incorrect) rule.

```css
/* repro.css */
.flex-row, .flex-col {
  display: flex;
  flex-direction: row;
}
```
