### ISSUE TITLE
CSS parser not supporting string form of font format/family

### ISSUE THREAD

**Issue by victorwedo** [oven-sh/bun#17264]
### What version of Bun is running?

1.2.2+c1708ea6a

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

1. Create a file `index.html`
    ```html
    <html>
      <head>
        <link rel="stylesheet" href="index.css" />
      </head>
    </html>
    ```
2. Create a file `index.css`
    ```css
    @font-face {
        font-family: 'Space Grotesk Variable';
        src: url(https://cdn.jsdelivr.net/fontsource/fonts/space-grotesk:vf@latest/latin-wght-normal.woff2) format('woff2-variations');
    }
    ```
3. Bundle with `bun build index.html --outdir build`, the built CSS file will be like this:
    ```css
    /* index.css */
    @font-face {
      font-family: Space Grotesk Variable;
      src: url("https://cdn.jsdelivr.net/fontsource/fonts/space-grotesk:vf@latest/latin-wght-normal.woff2") format(woff2-variations);
    }
    ```

### What is the expected behavior?

According to https://drafts.csswg.org/css-fonts/#font-face-src-parsing, `format("woff2-variations")` is equivalent to `format(woff2) tech(variations)`, but when Bun is bundling CSS files, it transforms `format("woff2-variations")` into `format(woff2-variations)` which is not recognized by browsers.

Same problem for `font-family`, quotes are deleted, but if the font name have whitespaces, then browsers won't recognize the font.
