### ISSUE TITLE
CSS `@import` and `url()` do not work in HMR

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#17329]
`url()` and `@import` in CSS files with HMR returns `import_record.path.text` instead of the unique_key. This causes it to output the absolute file path on disk in the output css file, which the server cannot serve (nor should it)

Input:
```css
body::before {
  content: "";
  position: fixed;
  inset: 0;
  z-index: -1;
  opacity: 0.05;
  background: url("./logo.svg");
  background-size: 256px;
  transform: rotate(-10deg) scale(1.4);
  animation: slide 120s linear infinite;
  pointer-events: none;
}
```

Output:
```css
body:before {
  content: "";
  position: fixed;
  z-index: -1;
  opacity: .05;
  animation: slide 120s linear infinite;
  pointer-events: none;
  background: url("/private/tmp/ok/src/logo.svg") 0 0 / 256px;
  inset: 0;
  transform: rotate(-10deg)scale(1.4);
}

```

Ideally, it would use source_index like JS. Then, we can defer worrying about what the correct URL is to the end and rewrite at the end all at once. We shouldn't be overwriting `source.path.text` either (unless it's to reuse an existing allocation of the same contents and free that one).
