### ISSUE TITLE
bunfig.toml Appears to be Ignored

### ISSUE THREAD

**Issue by travistrue2008** [oven-sh/bun#17664]
### What version of Bun is running?

1.2.3

### What steps can reproduce the bug?

Run `bun test` (with no arguments)

### What is the expected behavior?

Here's my `bunfig.toml` file:

```toml
[test]
coverage = true
coverageThreshold = 0.9
coverageDir = "./coverage"
coverageReporter = ["text", "lcov"]
preload = ["./test-setup.js"]
```

Given the config, executing `bun test` should:
- Output coverage stats in the terminal
- Coverage should be written to a file
- Invoke the test hooks that I've defined in `test-setup.js`

### What do you see instead?

- Code coverage isn't output to the terminal
- Code coverage isn't written to a file
- Test hooks aren't invoked

### Additional information

It looks like `bun` might not recognize `bunfig.toml` files in the current build. This did seem to work in the canary build that I installed on 2/22/25 though. CLI arguments for setting things like coverage and preload hooks still appear to work fine though. So, if I define `--coverage`, then it'll give me coverage, etc.
