### ISSUE TITLE
Add build config into bunfig.toml

### ISSUE THREAD

**Issue by michaeljota** [oven-sh/bun#18290]
### What is the problem this feature would solve?

Basic building configurations may not need for complex API, and a static file could be enough for that use case. 

### What is the feature you are proposing to solve the problem?

Integrating the build configuration into the bunfig.toml config file.
```toml
[build]
entrypoints = "./index.ts"
outdir = "code/bmbp_data_ui/static/"
watch = true
minify = true
externals = ["react", "react-dom", "@arco-design/web-react"]
```

### What alternatives have you considered?

This is a similar request as #13200, but instead of another config file, the configuration would be integrated into bunfig.toml.
