### ISSUE TITLE
ECONNRESET when posting large files using a proxy squid

### ISSUE THREAD

**Issue by rse-mfm** [oven-sh/bun#18490]
### What version of Bun is running?

1.2.6

### What platform is your computer?

Darwin 24.3.0 arm64 arm

or

Linux 5.15.0-124-generic x86_64 x86_64

### What steps can reproduce the bug?

Here's the files to reproduce the bug:

docker-compose.yml:
```
version: '3.8'

services:
  squid:
    image: ubuntu/squid:latest
    container_name: squid-proxy
    ports:
      - "3128:3128"

  bun-app:
    image: oven/bun:latest
    container_name: bun-app
    working_dir: /app
    volumes:
      - ./app:/app
    command: ["bun", "index.js"]
    environment:
      - HTTP_PROXY=http://squid:3128
      - HTTPS_PROXY=http://squid:3128
    depends_on:
      - squid
```

index.js:
```
import fs from "fs";

const filePath = "./file.txt"; // Path to the file you want to send
// Any server that accepts POST requests
const url = "https://webhook.site/fc07acff-a25f-422c-b85a-377432146524";

// Read the file to send in the POST request
const file = fs.readFileSync(filePath);

// Send the POST request using fetch
fetch(url, {
  method: "POST",
  headers: {
    "Content-Type": "application/octet-stream",
    "Content-Length": file.length.toString(),
    "Connection": "close",
  },
  body: file,
  verbose: "curl"
})
  .then((response) => response.text())
  .then((data) => console.log("Response:", data))
  .catch((error) => console.error("Error:", error));
```

Structure:
```
.
├── app/
│   ├── index.js           # Bun script to send POST request
│   └── file.txt           # The file to send with the request
├── docker-compose.yml     # Docker Compose configuration
```

I generated the file.txt using `cat /dev/random | head -n 10000 > file.txt`. 
The bug is reproducible with a few MB file. (I tested it with 2.5MB)

We do not have any problems with smaller files (few KB).

### What is the expected behavior?

We expect to have a successful POST file and status code 200.

### What do you see instead?

Here's the output log from bun with a ECONNRESET:

```
bun-app      | curl --http1.1 "https://webhook.site/fc07acff-a25f-422c-b85a-377432146524" -X POST -H "content-type: application/octet-stream" -H "Connection: keep-alive" -H "User-Agent: Bun/1.2.6" -H "Accept: */*" -H "Host: webhook.site" -H "Accept-Encoding: gzip, deflate, br" --compressed -H "Content-Length: 2603126"
bun-app      | > HTTP/1.1 POST https://webhook.site/fc07acff-a25f-422c-b85a-377432146524
bun-app      | > content-type: application/octet-stream
bun-app      | > Connection: keep-alive
bun-app      | > User-Agent: Bun/1.2.6
bun-app      | > Accept: */*
bun-app      | > Host: webhook.site
bun-app      | > Accept-Encoding: gzip, deflate, br
bun-app      | > Content-Length: 2603126
bun-app      |
bun-app      | < 200 Connection established
bun-app      |
bun-app      | Error: error: The socket connection was closed unexpectedly. For more information, pass `verbose: true` in the second argument to fetch()
bun-app      |   path: "https://webhook.site/fc07acff-a25f-422c-b85a-377432146524",
bun-app      |  errno: 0,
bun-app      |   code: "ECONNRESET"
bun-app      |
bun-app      |
bun-app exited with code 0
```

And the output log from Squid:

`squid-proxy  | 1742980871.196    541 192.168.117.3 TCP_TUNNEL/200 3786 CONNECT webhook.site:443 - HIER_DIRECT/178.63.67.153 -`

### Additional information

I reproduce it on MacOS and on Linux. The curl command output by bun is working.
