### ISSUE TITLE
Inconsistent hashing behavior with CSS animation names and keyframes in CSS modules

### ISSUE THREAD

**Issue by Iceman8911** [oven-sh/bun#18921]
### What version of Bun is running?

1.2.8+adab0f64f

### What platform is your computer?

Linux 6.1.0-30-amd64 x86_64 unknown

### What steps can reproduce the bug?

In a `test.module.css` file, I had this:

```css
.playAnim {
    animation: anim forwards ease-out 0.25s;
  }

@keyframes anim {
  0% {
    content: url("./../../../../../../media/img/general/envelope_closed.webp");
  }

  50% {
    content: url("./../../../../../../media/img/general/envelope_in-between.webp")
  }

  100% {
    content: url("./../../../../../../media/img/general/envelope_open.webp")
  }
}
```

### What is the expected behavior?

```css
.playAnim__****** {
    animation: anim_****** forwards ease-out 0.25s;
  }

@keyframes anim__****** {
  0% {
    content: url("data:image/webp;base64,UklGRpYAAABXRUJQVlA4TIoAAAAvf8AXEDUwjiSpDRlQ5B8jXyWA1Zn9aqQgbQMWZWf+559s0ibd6id8/g8qU09BrQLPTzsABXX+lUC+ADr//K3fRGSzceloR5lMSyfKYHq6ocimqVuKaLp6Q5FMW28pgunLgjxNY1bkYTqzJEvTmjVZmN486I1pzotuTHeetDPhhdiXWwW0mnoFpA8=");
  }

  50% {
    content: url("data:image/webp;base64,UklGRiABAABXRUJQVlA4TBQBAAAvf8AXEE9gKAIZ/Qgvg5Nhfsuhpm0k5vijOGr3jcBPbVDTNhJz/Hkcq5u+MWjTa/4DgNu+PjHTCKpCkSmb9f/gKpKtysECFrCAhbWAhbUQC1g4drlP4OQvqYrovyO3jRxJvnDzzKZHlJ/hAZ+jA9gCWgfqsQG9AfeL9KydAvCsCe4XSeOULCiaWh5OyMNkSB3JKSBzjATNdV0GecX1SVBtHakllFpvlaK68CYWAXgTW6okbWBfNDkYQxpy/dDQMkfjHJgWUQ7Mfd3DxNp4dWoqEVU+jkxEVoAzoitE8CUZ6gD0IRgRloE9zOirrETbiadXIi2JnL6k8H9kOM9P3BZ0Iuq2IWJv7wq5hr3t/b1V5uWV6xU=");
  }

  100% {
    content: url("data:image/webp;base64,UklGRiwBAABXRUJQVlA4TB8BAAAvf8AXEEdgKAIZ/eith5PBfsuhppEU6Pw7OHkPYICOUCiGJIlZf48lWoNLBul1Nf8BwK7fnti0gqZQZMr/g6vIduvGFERBFEyhFEQhFExBuG3JD93725mI/jtwG0mRsuRluHtFexx8Du1x4M5dVMUdH07af3Po6o4PqQx8KO2BD6Ez8FXrDvgqdQ98VXoDvgq9A9+raoDvRXXAd6ta4LtRPfCdhAFFIwqFwZD/oIMTNDq2PggS7Q4bugpFMvFBhikhKQAjmjYwW9m3fYLdM2wfIYqoHez2MXfnfaElqraouz5ZB9SIriP2R6dfMj5CEmE3sKs/rVkQbRWXDyLtEnei7RrxHNtcn7gnxJaoe8YSd4+Dqoiw9zz8vdUGeGjwGgA=");
  }
}
```

### What do you see instead?

```css
.playAnim__****** {
    animation: anim forwards ease-out 0.25s;
  }

@keyframes anim__****** {
  0% {
    content: url("data:image/webp;base64,UklGRpYAAABXRUJQVlA4TIoAAAAvf8AXEDUwjiSpDRlQ5B8jXyWA1Zn9aqQgbQMWZWf+559s0ibd6id8/g8qU09BrQLPTzsABXX+lUC+ADr//K3fRGSzceloR5lMSyfKYHq6ocimqVuKaLp6Q5FMW28pgunLgjxNY1bkYTqzJEvTmjVZmN486I1pzotuTHeetDPhhdiXWwW0mnoFpA8=");
  }

  50% {
    content: url("data:image/webp;base64,UklGRiABAABXRUJQVlA4TBQBAAAvf8AXEE9gKAIZ/Qgvg5Nhfsuhpm0k5vijOGr3jcBPbVDTNhJz/Hkcq5u+MWjTa/4DgNu+PjHTCKpCkSmb9f/gKpKtysECFrCAhbWAhbUQC1g4drlP4OQvqYrovyO3jRxJvnDzzKZHlJ/hAZ+jA9gCWgfqsQG9AfeL9KydAvCsCe4XSeOULCiaWh5OyMNkSB3JKSBzjATNdV0GecX1SVBtHakllFpvlaK68CYWAXgTW6okbWBfNDkYQxpy/dDQMkfjHJgWUQ7Mfd3DxNp4dWoqEVU+jkxEVoAzoitE8CUZ6gD0IRgRloE9zOirrETbiadXIi2JnL6k8H9kOM9P3BZ0Iuq2IWJv7wq5hr3t/b1V5uWV6xU=");
  }

  100% {
    content: url("data:image/webp;base64,UklGRiwBAABXRUJQVlA4TB8BAAAvf8AXEEdgKAIZ/eith5PBfsuhppEU6Pw7OHkPYICOUCiGJIlZf48lWoNLBul1Nf8BwK7fnti0gqZQZMr/g6vIduvGFERBFEyhFEQhFExBuG3JD93725mI/jtwG0mRsuRluHtFexx8Du1x4M5dVMUdH07af3Po6o4PqQx8KO2BD6Ez8FXrDvgqdQ98VXoDvgq9A9+raoDvRXXAd6ta4LtRPfCdhAFFIwqFwZD/oIMTNDq2PggS7Q4bugpFMvFBhikhKQAjmjYwW9m3fYLdM2wfIYqoHez2MXfnfaElqraouz5ZB9SIriP2R6dfMj5CEmE3sKs/rVkQbRWXDyLtEnei7RrxHNtcn7gnxJaoe8YSd4+Dqoiw9zz8vdUGeGjwGgA=");
  }
}
```
in `index.css` after running `bun build` on the typescript file that imported `playAnim`. 

### Additional information

Trying `.playAnim { animation-name: anim; }` didn't work out too.

Also, even though the keyframe and `playAnim` were in the same `module.css` file, they generated with different hashes.
