### ISSUE TITLE
SegmentationFault at 0 when adding entry to `[install.scopes]` in `bunfig.toml`

### ISSUE THREAD

**Issue by biw** [oven-sh/bun#190]
Hey Jarred, awesome work on bun! I found an error that I was able to recreate in a yarn project and after using `bun create`.

To recreate add an entry to `[install.scopes]` in `bunfig.toml`:
```toml
# bunfig.toml
[install.scopes]
mybigcompany2 = { token = "123456" }
```

Error:
```
SegmentationFault at 0


–––– bun meta ––––
Bun v0.0.83 macOS x64 21.4.0
InstallCommand: bunfig
Elapsed: 21ms | User: 20ms | Sys: 15ms
RSS: 20.95MB | Peak: 20.95MB | Commit: 0.27GB | Faults: 0
–––– bun meta ––––
```
