### ISSUE TITLE
Add --fetch-preconnect option to `bunfig.toml`

### ISSUE THREAD

**Issue by i-love-neko-girls** [oven-sh/bun#19217]
### What is the problem this feature would solve?

It's not such convenient to specify it every time in CLI options 

### What is the feature you are proposing to solve the problem?

add something like this to bunfig.toml:

```toml
[run]
fetch-preconnect = "https://example.com/"
fetch-preconnect = ["https://example.com/", "https://example2.com/"]
```
