### ISSUE TITLE
How to exclued a file from bun test coverage

### ISSUE THREAD

**Issue by manastunga787** [oven-sh/bun#19494]
### Excluding files from test coverage.

Test coverage in bun also including the setup.ts file. how to exclude a file from test coverage.

 **bunfig.toml file**

```toml
[test]
preload = ["./setup.ts"]

#test root directory

coverage = true
root = "src/test"
# Set specific thresholds for different coverage metrics
coverageThreshold = {lines = 0.9, functions = 0.9, statements = 0.9}
# skipping tests files (themselves) from coverage report
coverageSkipTestFiles = true

coverageExclude = [
  "./setup.ts",
]
```
when i run bun test it produces coverage report that includes setup file also

### What is the feature you are proposing to solve the problem?

there should be an option to exclude the files from test coverage like

```toml
coverageExclude = [
  "./setup.ts",
]
```

### What alternatives have you considered?

Related to #7662

_No response_
