### ISSUE TITLE
CSS custom properties with multiple rgba() colors are transcoded incorrectly

### ISSUE THREAD

**Issue by egnor** [oven-sh/bun#19546]
### What version of Bun is running?

1.2.12+32a47ae45

### What platform is your computer?

Linux 6.12.3-061203-generic x86_64 x86_64

### What steps can reproduce the bug?

1. create test.css:
```css
div {
  --foo: 1 1 1 rgba(1, 1, 1, 0.1), 2 2 2 rgba(2, 2, 2, 0.2);
  --bar: 1 1 1 #01010116, 2 2 2 #02020233;
  box-shadow: 1 1 1 rgba(1, 1, 1, 0.1), 2 2 2 rgba(2, 2, 2, 0.2);
}
```

2. run `bun build test.css` - I get this:
```css
/* test.css */
div {
  --foo: 1 1 1 , 2 2 2 #02020233;
  --bar: 1 1 1 #01010116, 2 2 2 #02020233;
  box-shadow: 1px 1px 1px #0101011a, 2px 2px 2px #02020233;
}
```

### What is the expected behavior?

Expected: all three lines (the `--foo` and `--bar` custom properties, plus the specific `box-shadow` property) retain the specification correctly (perhaps converted from rgba to #xxxxxxxx for brevity)

### What do you see instead?

Actual: the `--foo` line in particular has the first `rgba(...)` spec completely lost:
```css
  --foo: 1 1 1 , 2 2 2 #02020233;
```

In general it seems to lose all but the last `rgba(...)` spec. Note that `#xxxxxxxx` specs (as in `--bar`) are preserved correctly, as are `rgba(...)` specs in specific properties (as in `box-shadow:`).

### Additional information

This affects [Pico CSS](https://picocss.com/), which uses custom properties extensively for light/dark mode management, including box shadow specifications, and things end up looking very strange because the colors default to bright white.
