### ISSUE TITLE
Bun builder incorrectly removes css classes. (`border-start-start-radius` and `border-end-start-radius`)

### ISSUE THREAD

**Issue by Jezza** [oven-sh/bun#19597]
### What version of Bun is running?

1.2.14-canary.2+0a0205be6

### What platform is your computer?

Linux 6.5.0-0.deb12.1-amd64 x86_64 unknown

### What steps can reproduce the bug?

Copy the follow into a file (ie test.css):

```css
.field {
    border-start-start-radius: 0;
    border-end-start-radius: 0;
    background: red;
}

.other-field {
    background: black;
}
```

Compile it via `bun build ./test.css`

### What is the expected behavior?

I would expect the bundler to emit the css with those properties.

### What do you see instead?

```css
/* test.css */
.field {
  background: red;
}

.other-field {
  background: #000;
}
```
It omits the `border-start-start-radius` and `border-end-start-radius` properties completely.

### Additional information

(Another plus would be a way to tell the bundler to not omit unknown properties. (assuming that's the bug))
