### ISSUE TITLE
radians rewritten to degrees without converting

### ISSUE THREAD

**Issue by 190n** [oven-sh/bun#19619]
### What version of Bun is running?

1.2.13+64ed68c9e

### What platform is your computer?

Darwin 24.4.0 arm64 arm

### What steps can reproduce the bug?

Create a CSS file containing radians, e.g.:

```css
/* bun.css */
.bun {
    transform: rotate(1rad);
}
```

Build it: `bun build bun.css`

### What is the expected behavior?

The amount `1rad` should be passed through unmodified (or perhaps converted to degrees, but that would be imprecise and result in more characters)

### What do you see instead?

`1rad` is rewritten to `1deg`, which is not the same value (a radian is around 57 degrees):

```css
/* bun.css */
.bun {
  transform: rotate(1deg);
}
```
