### ISSUE TITLE
`process` and `import` are undefined in front end code

### ISSUE THREAD

**Issue by Nanome203** [oven-sh/bun#20071]
### What version of Bun is running?

1.2.15+df017990a

### What platform is your computer?

Linux 6.14.7-arch2-1 x86_64 unknown

### What steps can reproduce the bug?

bunfig.toml:

```toml
[serve.static]
plugins = ["bun-plugin-tailwind"]
env = "BUN_PUBLIC_*"
```

Then add this to front end code and run
```ts
const HOST = process.env.BUN_PUBLIC_HOST_URL;
const PORT = import.meta.env.BUN_PUBLIC_PORT;
```

### What is the expected behavior?

environment variables are read

### What do you see instead?

`process is undefined`
`hmr.importMeta.env is undefined`
