### ISSUE TITLE
(bug): .bunfig.toml file Priority issue

### ISSUE THREAD

**Issue by luzilong2005** [oven-sh/bun#20390]
### What version of Bun is running?

1.2.16

### What platform is your computer?

Microsoft Windows 11 10.0.26200 x64

### What steps can reproduce the bug?

.bunfig.toml:
``` toml
[install.cache]
dir = "D:/bun/Cache"
disable = false
```

.npmrc:
```ini
cache = "D:/npm/Cache"
```

What is printed using 'bun pm cache -g' is' D:\npm\Cache '.
If '.npmrc 'is not configured, what is printed is' D:\bun\Cache'.

When there is a '.bunfig.toml 'file, the file configuration of this file should be used.
