### ISSUE TITLE
Bundler incorrectly handles CSS @layer declarations without assigned styles

### ISSUE THREAD

**Issue by moonjellydigital** [oven-sh/bun#20546]
### What version of Bun is running?

1.2.17+282dda62c

### What platform is your computer?

Linux 6.8.0-1026-oracle aarch64 aarch64

### Description

When bundling stylesheets with cascade layers that are declared without assigning styles, the bundler leaves the layer declarations and import statements at the bottom of the bundled stylesheet.

### Steps To Reproduce

1. Create the following files and their contents in the project root:

`index.html`:

```html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Test</title>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, width=device-width">
    <link rel="stylesheet" href="./main.css">
  </head>
  <body>
    <h1>Hello, Test.</h1>
  </body>
</html>
```

`a.css`:

```css
body {
  margin: 0;
}
```

`b.css`:

```css
h1 {
  font-family: sans-serif;
}
```

`c.css`:

```css
.text-centered {
  text-align: center;
}
```

`main.css`:

```css
@layer one;
@layer two;
@layer three;

/* OR declare the layers with the syntax on the next line, the same bug happens. */
/* @layer one, two, three; */

@import url('./a.css') layer(one);
@import url('./b.css) layer(two);
@import url('./c.css) layer(three);
```

2. Run `bun ./index.html` OR `bun build ./index.html --outdir=out` OR `bun build ./main.css --outdir=out`.

### What is the expected behavior?

The expected behavior is that the bundler doesn't leave the layer declarations and import statements at the bottom of the bundled stylesheet. Other than that, the bundled CSS is correct.

### What do you see instead?

Bundler output with cascade layers declared with separate `@layer` statements:

```css
/* a.css */
@layer one {
  body {
    margin: 0;
  }
}

/* b.css */
@layer two {
  h1 {
    font-family: sans-serif;
  }
}

/* c.css */
@layer three {
  .text-centered {
    text-align: center;
  }
}

/* main.css */
@layer one;
@layer two;
@layer three;
@import "./a.css" layer(one);
@import "./b.css" layer(two);
@import "./c.css" layer(three);
```

Output with multiple layers declared in one `@layer` statement:

```css
/* a.css */
@layer one {
  body {
    margin: 0;
  }
}

/* b.css */
@layer two {
  h1 {
    font-family: sans-serif;
  }
}

/* c.css */
@layer three {
  .text-centered {
    text-align: center;
  }
}

/* main.css */
@layer one, two, three;
@import "./a.css" layer(one);
@import "./b.css" layer(two);
@import "./c.css" layer(three);
```

### Additional information

- This bug was also present on Bun v1.2.16.
- Cascade layers that are defined with styles do bundle correctly, it's _only_ layers declared without styles that are affected.
