### ISSUE TITLE
Color-scheme rules inside @layer do not inject --buncss-light / --buncss-dark variables

### ISSUE THREAD

**Issue by mech-tools** [oven-sh/bun#20689]
### What version of Bun is running?

1.2.17+282dda62c

### What platform is your computer?

Linux 6.6.87.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```css
/* input.css */
@layer shm.colors {
  body.theme-dark {
    color-scheme: dark;
  }

  body.theme-light {
    color-scheme: light;
  }
}
```

#### Build command
bun build input.css

### What is the expected behavior?

```css
@layer shm.colors {
  body.theme-dark {
    --buncss-light: ;
    --buncss-dark: initial;
    color-scheme: dark;
  }

  body.theme-light {
    --buncss-light: initial;
    --buncss-dark: ;
    color-scheme: light;
  }
}
```

### What do you see instead?

```css
@layer shm.colors {
  body.theme-dark {
    color-scheme: dark;
  }

  body.theme-light {
    color-scheme: light;
  }
}
```

### Additional information

- The issue only occurs when placing the rules inside an @layer block.
- Without @layer, Bun correctly injects the theme-related CSS variables.
- This breaks consistency for dark/light theming support when structuring CSS with layers.
