### ISSUE TITLE
Private, Scoped NPM Packages Only Work Locally, Not With GitHub Actions

### ISSUE THREAD

**Issue by mangs** [oven-sh/bun#3241]
### What version of Bun is running?

0.6.7

### What platform is your computer?

Darwin 22.5.0 x86_64 i386

### What steps can reproduce the bug?

Using the following workflow fails when trying to install private packages via [GitHub Packages](https://github.com/features/packages):

```yaml
name: Push Workflow
on: push

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"
          registry-url: https://npm.pkg.github.com
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "0.6.7"
      - run: |
          echo "[install.scopes]" > ~/.bunfig.toml
          echo "\"@scope\" = { token = \"${{ secrets.PACKAGES_TOKEN }}\", url = \"https://npm.pkg.github.com\" }" >> ~/.bunfig.toml
          cat ~/.bunfig.toml # Debug output to check file contents
      - run: bun install
```

The `cat ~/.bunfig.toml` matches my local `.bunfig.toml` file exactly, and private packages install locally just fine. However, on GitHub Actions all private, scoped packages are skipped.

### What is the expected behavior?

All public and private packages are installed as they are locally

Ideally Bun could mimic NPM behavior to carry on its tradition of being a drop-in replacement. Specifically, NPM exposes a `NODE_AUTH_TOKEN` environment variable that works along with the `registry-url` config option of `actions/setup-node`. For example:

```yaml
...
- uses: actions/setup-node@v3
  with:
    node-version: "18.16.0"
    registry-url: https://npm.pkg.github.com
...
- run: npm ci
  env:
    NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
...
```

### What do you see instead?

`401` responses for each private package (redacted because they're private company packages)

```
bun install v0.6.7 (59d7c47e)

GET https://npm.pkg.github.com/download/@scope/package1/5.2.2/c20b3c572b3509b0993221adee8d05c36dc53165 - 401

GET https://npm.pkg.github.com/download/@scope/package2/1.1.6/0ecb1cba6c0218b1a6b6cbb6dc29ba6e8a463951 - 401
```

### Additional information

For packages that do install, Bun is super fast. Keep up the great work! =D
