### ISSUE TITLE
Bun not using expected version of dependency during Github action workflow

### ISSUE THREAD

**Issue by aatecey** [oven-sh/bun#3932]
### What version of Bun is running?

0.7.1

### What platform is your computer?

Ubuntu 22.04.2 LTS - Github action runner

### What steps can reproduce the bug?

As a dependency of my project it has directly prettier@3.0.0 but has older versions of prettier as sub-dependencies of other packages. So there is 3.0.0, 2.7.1 and 1.19.1.

I'm using bun as the package manager and run a Github action workflow to run prettier.

```yaml
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install --frozen-lockfile
      - run: bun prettier -v
      - run: bun format --check
```

From the CI run I can see prettier@3.0.0 install:

```
bun install v0.7.1 (53cc4df1)
...
 + prettier@3.0.0
...
```

The version check step though outputs:
```
Run bun prettier -v
2.7.1
```

Sometimes it will run 3.0.0 and sometime 1.19.1.

Checked `node_modules/.bin/prettier` symlink on the failed runs:
```
lrwxrwxrwx 1 runner docker 59 Aug  2 21:49 prettier -> ../@storybook/codemod/node_modules/prettier/bin-prettier.js
```
and on good runs:
```
lrwxrwxrwx 1 runner docker 28 Aug  2 21:44 prettier -> ../prettier/bin/prettier.cjs
```

### What is the expected behavior?

I would expect it to use version 3.0.0 100% of the time.

### What do you see instead?

Sometimes it will run 3.0.0, 2.7.1 or 1.19.1. Re-running the same job can result in different version being used.
