### ISSUE TITLE
Deployment section on how to deploy to various hosts

### ISSUE THREAD

**Issue by venkatd** [oven-sh/bun#4144]
### What is the type of issue?

Documentation is missing

### What is the issue?

It took me some time to figure out how to deploy bun to my host. I think it would be valuable to newcomers if guides or templates were provided on how to deploy bun.

I can start by sharing our `render.yaml` blueprint specification on how to deploy to render.com:

```yaml
services:
  - type: web
    name: myapp-server
    branch: main
    env: node
    plan: free
    rootDir: apps/myapp-server
    buildCommand: export PATH="$BUN_INSTALL/bin:$PATH" && curl -fsSL https://bun.sh/install | bash && bun install
    startCommand: export PATH="$BUN_INSTALL/bin:$PATH" && bun run src/index.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: BUN_INSTALL
        value: /opt/render/project/.bun
      - key: DATABASE_URL
        fromDatabase:
          name: myapp-database
          property: connectionString

databases:
  - name: myapp-database
    plan: free
    postgresMajorVersion: 15
```

If it helps, I could later share sample hello-world repo for deploying a bun monorepo to render.com
