### ISSUE TITLE
Global configuration from a config file does not seem to apply

### ISSUE THREAD

**Issue by jmcantrell** [oven-sh/bun#4553]
### What version of Bun is running?

0.8.1

### What platform is your computer?

Darwin 21.6.0 x86_64 i386
Linux 6.4.12-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

Create a config file with something like the following:

```toml
[install]
globalDir = "~/.bun-alt/install/global"
globalBinDir = "~/.bun-alt/bin"
```

Install a global package like: `bun --config=/path/to/config.toml add -g prettier`

### What is the expected behavior?

Bun should install the package to `~/.bun-alt`.

### What do you see instead?

Bun installs the package to the default directory, `~/.bun`.
