### ISSUE TITLE
bun is not able to log into private jfrog registry via npmAuth

### ISSUE THREAD

**Issue by patrik-elekes-mck** [oven-sh/bun#4903]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Hi everyone, We have a private registry. We install all of the packages from the original registry (npm org) expect two that are ours in a jfrog registry. In the current solution we use `.npmrc` file that works perfectly. 

With this `bun` config we are not able to auth into the registry (at least we got error 401):
> error: unauthorized "pino" <url from jfrog> 401
error: pino@^8.12.0 failed to resolve

url: `https://organization.jfrog.io/artifactory/api/npm/namespace-npm/`
url in error: `organization.jfrog.io/artifactory/api/npm/namespace-npm/pino`

`.npmrc` file:
```
@ici:registry="<URL>"
//<URL>:_auth=${JFROG_AUTH}
//<URL>:always-auth=true

save-exact=true
```

.bunfig.toml` file:

```toml
[npmAuth."<registry url from .npmrc>"]
_auth = "$JFROG_AUTH"
alwaysAuth = true

[install]
registry = { token = "$TOKEN",  url = "<registry url from .npmrc>"}

[install.scopes]
"@ici:registry" = { token = "$TOKEN",  url = "<registry url from .npmrc>"}
# "@ici" = { token = "$TOKEN",  url = "<registry url from .npmrc>"}
```

`JFROG_AUTH` and `NPM_AUTH` are in the `.env` file but I tried to copy into into the toml file.

I tried a lot of combination but I am not able to figure out this issue.

I ma not a admin in jfrog, so I am not able to check and share the jfrog config :( 

Problems:
1. We are not able to auth into our jfrog registry.
2. We do not know how to set the registry for specific packages.

### What is the expected behavior?

All of the packages are installed. Some of them from the original npm org registry, some of them from our Jfrog instance.

### What do you see instead?

```
bun install 
[0.05ms] ".env"
bun install v1.0.0 (822a00c4)
  🔍 natural-compare [1/197] 
error: unauthorized "pino" <url from jfrog> 401
...
error: pino@^8.12.0 failed to resolve
...
```

**Comment by chrisbodhi** [comment]
@patrik-elekes-mck Did you resolve this? I'm running into a similar issue, and have also tried lots of combinations to get this working.

**Comment by itsgoofer** [comment]
Worked for me by generating a new token and use this one line:

```toml
[install]
registry = { token = "token", url = "registry_url_from_npmrc" }
```
