### ISSUE TITLE
Bun doesn't build correctly on CI

### ISSUE THREAD

**Issue by nacimgoura** [oven-sh/bun#4912]
### What version of Bun is running?

1.0.15 (b3bdf22e)

### What platform is your computer?

docker image oven:bun (inux 4.11.0-14-generic x86_64 unknown in CI)

### What steps can reproduce the bug?

I run a job in CI (Gitlab Runner) for build Vite but doesn't work (no logs and the script runs continuously)
The same command work correctly in local

```yml
build:
  stage: build
  script:
    - bun install --frozen-lockfile --silent
    - bun vite build
  artifacts:
    paths:
      - dist
```

### What is the expected behavior?

Bun build vite correctly

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/9990521/abcbfdd3-d6b4-4aaf-bc20-cf5716ecca33)
