### ISSUE TITLE
GitHub Action bunx: command not found

### ISSUE THREAD

**Issue by serhii-chernenko** [oven-sh/bun#4961]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

ubuntu-latest

### What steps can reproduce the bug?

I used your docs to build an app with Vite:
https://bun.sh/guides/ecosystem/vite

And I use the Vite docs to create a workflow for GitHub Actions:
https://vitejs.dev/guide/static-deploy.html#github-pages

The created `package.json` file contains the command `build`. 
It replaced it from
```vite build```
to
```bunx --bun vite build```

I saw the output error after the job of GitHub Actions:
<img width="522" alt="image" src="https://github.com/oven-sh/bun/assets/28815318/e7d17c11-3e1a-4a52-b73e-2165ff72dc8d">

main.yml:
```yml
name: Build TS React App with Bun and Vite

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run build
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with: 
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
```

package.json:
```json
{
  "name": "bun",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "bunx --bun vite",
    "build": "tsc && bunx --bun vite build",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/react": "^18.2.15",
    "@types/react-dom": "^18.2.7",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "@vitejs/plugin-react-swc": "^3.3.2",
    "eslint": "^8.45.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.3",
    "typescript": "^5.0.2",
    "vite": "^4.4.5"
  }
}
```

### What is the expected behavior?

`bunx` command has to be available for GitHub actions as well as on my local machine

### What do you see instead?

I see failed job
