### ISSUE TITLE
Private registry scoped package add fails due to forward slash not being encoded

### ISSUE THREAD

**Issue by jbidston** [oven-sh/bun#5076]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

MacOS - Darwin 22.1.0 x86_64 i386

### What steps can reproduce the bug?

Private NPM Registry AWS CodeArtifact, used for both private packages and to proxy public.

**bunfig.toml**
```toml
[install]
registry = {
	url = "https://something.d.codeartifact.somewhere.amazonaws.com/npm/repository/",
	token = "eabyJ2 ... w7d5Hy4A"
}
```
(also tried many, many varied configuration syntax)
```toml
[install]
registry = {
	url = "https://something.d.codeartifact.somewhere.amazonaws.com/npm/repository/:_authToken=eabyJ2 ... w7d5Hy4A"
}
```

Install **any** scoped package, for example `@storybook/addons`.

```bash
bun add @storybook/addons
```

### What is the expected behavior?

Storybook Addons package is installed successfully, enabled by a successful GET request to:

`https://something.d.codeartifact.somewhere.amazonaws.com/npm/repository/@storybook%2Faddons`

Please note the `storybook%2Faddons` forward slash is URL encoded.

### What do you see instead?

Storybook Addons package is **not** installed successfully.

GET request to:

`https://something.d.codeartifact.somewhere.amazonaws.com/npm/repository/@storybook/addons`

... results in a `400 Bad Request`

Please note the `storybook/addons` forward slash is not URL encoded.

After `bun install` all non-scoped packages install successfully, and all scoped packages are listed:

```bash
...
error: @storybook/addon-a11y@^6.5.16 failed to resolve
error: @storybook/addon-essentials@^6.5.16 failed to resolve
error: @storybook/addons@^6.5.16 failed to resolve
error: @storybook/components@^6.5.16 failed to resolve
error: @storybook/react@^6.5.16 failed to resolve
error: @storybook/theming@^6.5.16 failed to resolve
...
```

### Additional information

I think that this issue is being discussed in the comments of #643, and it may improve clarity having a dedicated issue.

While I am using AWS Code Artifact, #643 suggests it is not limited to this artifact repository.
