### ISSUE TITLE
case insensitive scopes - private registry packages

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#5189]
```toml
[install]
registry = "https://registry.npmjs.org"

[install.scopes]

"@randomscope" = { token = "$NPM_TOKEN", url = 'https://npm.pkg.github.com' }

```
I have an edge case when an internal package package.json name property pascalcase or all lowercase and when defining the scope name in the toml config I get this error

```bash
uh-oh: internal: package name mismatch expected "@randomscope/lib" but received "@randomScope/lib"
bun will crash now 😭😭😭
```

the mixture of names on my side is my fault and will correct but i couldn't find a raised issue (maybe i didn't try hard enough) where scopes are case insensitive or is this a known issue?

```bash
----- bun meta -----
Bun v1.0.0 (822a00c4) macOS Silicon 22.6.0
InstallCommand: dotenv bunfig 
HTTP: 155
Elapsed: 897ms | User: 100ms | Sys: 238ms
RSS: 86.93MB | Peak: 86.93MB | Commit: 109.08MB | Faults: 379
----- bun meta -----

0   0x102322624 WTFGetBacktrace
1   ??? Bun__crashReportDumpStackTrace
```

_Originally reported on Discord: [`case insensitive scopes - private registry packages`](https://discord.com/channels/876711213126520882/1150879457922531432/1150879457922531432)_
