### ISSUE TITLE
Custom Registry Support for `bunx` Commands

### ISSUE THREAD

**Issue by guenaydin** [oven-sh/bun#5361]
### What is the problem this feature would solve?

The problem that this feature would solve is the inconsistency and inconvenience experienced by developers when working with bunx commands in conjunction with custom registries. Currently, while developers can set up custom registries for dependency installation, bunx commands do not honor these custom registry settings. As a result, bunx commands continue to fetch packages from the default npm registry, causing issues and discrepancies in the development workflow.

### What is the feature you are proposing to solve the problem?

The feature proposed to solve the problem is the addition of a new configuration option within the `bunfig.toml` file. Specifically, this feature suggests the introduction of a `[bunx]` section in the configuration file, where users can specify a custom registry to be used for Bunx commands.

### What alternatives have you considered?

While proposing the feature of adding a `[bunx]` section to the `bunfig.toml` configuration file to specify a custom registry for bunx commands, there are a few alternative approaches that could be considered:

1. **Global Configuration Option:** Instead of a `[bunx]` section, one alternative could be to introduce a global configuration option in the `[registry]` section of the `bunfig.toml` file that would apply to both dependency installation and bunx commands. This would eliminate the need for a separate `[bunx]` section and could simplify the configuration file.

2. **Command-Line Flag:** Another approach could be to allow developers to specify the custom registry for bunx commands using a command-line flag when running bunx commands. For example, developers could run `bunx --registry my-custom-registry` to specify the registry for that specific command execution.

3. **Environment Variable:** An alternative approach could involve using an environment variable to set the custom registry for bunx commands. Developers could set an environment variable like `BUNX_REGISTRY=my-custom-registry` before running bunx commands, and bunx would use this registry for that session.

**Comment by eemelipa** [comment]
How about `bunx` would use the same `[install]` configuration options as `bun install` does?

Then both of them would be fully consistent and there wouldn't be need to duplicate the configuration

**Comment by haozi** [comment]
is that resolved?

**Comment by petertonysmith94** [comment]
For people having trouble with this, I managed to work around this by using a `.bunfig.toml` file.

```toml
[install.scopes]

# as an object with token
"@ScopedOrg" = { token = "$npm_token", url = "https://npm.pkg.github.com/" }
```

- Mac users: you can store this in your $HOME directory (`$HOME/.bunfig.toml`)
- Linux users: you can store this in your $XDG_CONFIG_HOME directory (`$XDG_CONFIG_HOME/.bunfig.toml`)
- Windows users: please research yourself 😄 

This also allowed me to authenticate to GH packages within GH actions for bun

```yaml
jobs:
  integration:
    steps:
      - name: Create .bunfig.toml
        run: |
          cat << EOF > "$XDG_CONFIG_HOME/.bunfig.toml"
          [install.scopes]

          # as an object with token
          "@ScopedOrg" = { token = "$npm_token", url = "https://npm.pkg.github.com/" }
          EOF
        env:
          npm_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Running test for bun create
        run: |
          bun create @ScopedOrg/package@next test-project --no-install
        env:
          npm_token: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
