### ISSUE TITLE
Need to redeclare default registry with scopes

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#5497]
Took a longggg time to get this working with multiple registries (GitHub private, and npm public), but eventually got there.

> Because GitHub doesn't forward a MISS to npm

If adding a scoped registry, **you have to** redeclare the default registry!

```toml
[install]
registry = "https://registry.npmjs.org" # redeclare default!

[install.scopes]
"@acme" = { token = "$ACME_TOKEN", url = "https://npm.pkg.github.com/" }
#                     ^ loads from .env file(s)
# add any other scoped registries (with their own access tokens)

```

_Originally posted by @lukeed in https://github.com/oven-sh/bun/issues/4654#issuecomment-1721791581_
