### ISSUE TITLE
Missing GitLab example

### ISSUE THREAD

**Issue by melroy89** [oven-sh/bun#5574]
### What is the type of issue?

Documentation is missing

### What is the issue?

Only showing a GitHub example of CI/CD, but no GitLab???

### Where did you find it?

https://bun.sh/docs/cli/install#ci-cd

**Comment by melroy89** [comment]
Ps. I notice that `bun install --cache-dir .bun` didn't create a `.bun` folder... Anyhow, now I just use `bun install`, example for GitLab with caching:

```yaml
default:
  image: oven/bun:1.0
  cache:
    key:
      files:
        - bun.lockb
    paths:
      - node_modules/
   before_script:
      - bun install

lint:
   script: 
     - bun run lint

audit:
   script: 
     - bun audit # Once bun also supports audit...?
```

If you wish you can also use `key: $CI_COMMIT_REF_SLUG` instead of looking at the hash of `bun.lockb`.
