### ISSUE TITLE
--watch and --hot doesn't work when using Bun in certain network environments

### ISSUE THREAD

**Issue by shelterit** [oven-sh/bun#5841]
### What is the problem this feature would solve?

The --watch and --hot options don't work when there's no file system support for directory events, like inside (Docker) containers or with Windows mounts. We use Bun containers with mounted dev file systems, and this is a problem especially for any developer with a Windows machine.

### What is the feature you are proposing to solve the problem?

Either;

1. Support polling in the --watch and --hot implementation, or
2. Expose a simple API for Bun to do the watch triggering but from an external source, for example;
   * Bun.reload(path);
   * Bun.hotload(path);

(I did try to make a bridge between the node:fs.watch and Chokidar, but found no easy way to transfer triggering, or to de-duplicate events / listeners)

### What alternatives have you considered?

I've made this solution (https://gist.github.com/shelterit/ab80a39bc28c86b52c48568ca50fa089) using Chokidar (as a watcher instead), the Bun Loader and require() which feels ... clunky. I'm sure there's a better way, and it would be great to tap into whatever smarts Bun uses for hotloading.

**Comment by jumoog** [comment]
`--watch` uses `inotify` which doesn't work with network mounts.  The only option that works in this case is polling.

**Comment by medeiroshudson** [comment]
This explains a lot i why was impossible to use `--hot` or `--watch` on Bun installed on Windows WSL.
Thanks for sharing Chokidar alternative

**Comment by pragmatta** [comment]
I guess from the user perspective doesn't matter that much how it works if it works but some comments:
- Since this is dev time resource use, I'm not too concerned on optimization. If there's significant performance impact, separate --poll or something might be in order.
- Reliability is probably more important, determining what needs reloading to correctly refresh things.
- I would prefer it to be a built-in option whatever the solution is. Trying to troubleshoot/optimize parameters of an addon for this is the kind of side track that kills productivity.
- Would be good to get an error/warning on this "trying to watch a wsl mount does not work, use -poll instead". Also maybe a guide, "if you use Bun over WSL and want edit code in Windows, this is the best way right now".
- I guess it's also a question if WSL is a long term solution or a stopgap waiting for the native Windows build. Or if the need to support mounts that don't have inotify is actually a long term need also in Linux/Mac.

**Comment by shelterit** [comment]
I have to say that the time it took to figure out even the basics was exhausting; days went by looking for clues, and I think I found the connecting bits as a footnote in some node.js API documentation. And it's all the more important given there's no Bun Windows support (apart from a partial alpha), so a *lot* of us will run it in containers with mounted systems where --watch and --hot don't work.

I think exposing the reload / hotload as API endpoints is a fairly reasonable and trivial point, enabling developers to find fixes where the built-in support falls down. I'm still struggling to reload properly as the Chokidar paths are relative but the keys in the Bun's Loader.registry are absolute, and the Loader.resolve can't find them (unless I trigger from the right path, which isn't always easily done), and yes, looking into the other resolvers as well. 

Bun solves some really huge issues, and I know there's a lot of focus on speed and performance, but for me the two main reasons for why the world needs Bun are 1) import/require working in harmony, and 2) natively speaks any JS dialect; it solves the MAIN issues in the JS world right now, just need to sort out this tiny little thing ... :)

**Comment by ThomasBurgess2000** [comment]
Has there been any progress here, is Chokidar still the current solution?

**Comment by vimercati-samir** [comment]
The bun --watch in my use case works with docker, it was just a question of setting the right volume binding in the docker-compose, this is repo structure: 

  - apps
    - indexer
      - Dockerfile.dev
      - src
        - index.ts
    - other_apps
  - packages
  - tooling
  - package.json
  - bun.lockb
  - turbo.json
  - docker-compose.dev.yml

this is the Dockerfile.dev:

```
FROM oven/bun:1 as build

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y git

COPY package.json bun.lockb turbo.json ./

COPY apps ./apps
COPY packages ./packages
COPY tooling ./tooling
  
RUN bun install

WORKDIR /usr/src/app/apps/indexer

CMD ["bun", "--watch", "src/index.ts"]

```

and this is the  docker-compose.dev.yml:

```
version: '3.8'
services:
  indexer:
    build:
      context: .
      dockerfile: apps/indexer/Dockerfile.dev
    volumes:
      - ./apps/indexer:/usr/src/app/apps/indexer
    env_file:
      - apps/indexer/.env.local  
    ports:
      - 8080:8080
```

when I run the command in the terminal `docker-compose -f docker-compose.dev.yml up`, and then I change the index.ts (that is the entry of my indexer app) it does hot reload correctly. Hope it helps!

**Comment by Moe03** [comment]
+1 --watch and --hot don't work on WSL

**Comment by KH93b** [comment]
bun --watch --poll index.tsx  
Is this supposed to be a solution to the problem? It doesn't work for me. How to do pooling?

**Comment by KH93b** [comment]
import { Elysia } from 'elysia';
import { watch } from 'chokidar';

const app = new Elysia().get('/', () => 'Hello Elysia').listen(3000);

const __appdir = import.meta.dir;

const __watcher = watch(__appdir, {
	ignored: /(^|[\/\\])\../, // ignore dotfiles
	persistent: true,
	usePolling: true,
	interval: 800,
	depth: 5,
	binaryInterval: 1300,
});

__watcher
	.on('add', path => console.log(`File ${path} has been added`))
	.on('change', path => {
		console.log(`File ${path} has been changed`);
		const key: string = Loader.resolve(path, path);
		console.log('key', key);
		Loader.registry.delete(key);
		require(path);
	});

console.log(
	`🦊 Elysia is FFFFQff running at ${app.server?.hostname}:${app.server?.port}`
);   

My code works correctly only once, if you make a change in the file a second time and then the server does not see the change. (bun in docker)

**Comment by AdityaT-19** [comment]
Hey guys I think I have found solution to the docker --hot problem

instead of using the volumes to persist the files we have to use docker compose watch

here is my file tree

```
anime-recom-backend/
┣ data/
┃ ┣ anime_movies.csv
┃ ┗ anime_series.csv
┣ db-data/
┣ server/
┃ ┣ drizzle/
┃ ┃ ┣ meta/
┃ ┃ ┃ ┣ 0000_snapshot.json
┃ ┃ ┃ ┗ _journal.json
┃ ┃ ┗ 0000_zippy_mimic.sql
┃ ┣ src/
┃ ┃ ┣ db/
┃ ┃ ┃ ┣ connection.ts
┃ ┃ ┃ ┣ migration.ts
┃ ┃ ┃ ┣ populate.ts
┃ ┃ ┃ ┣ queries.ts
┃ ┃ ┃ ┗ schema.ts
┃ ┃ ┗ index.ts
┃ ┣ .dockerignore
┃ ┣ .gitignore
┃ ┣ bun.lockb
┃ ┣ Dockerfile
┃ ┣ package.json
┃ ┣ README.md
┃ ┗ tsconfig.json
┣ .env
┗ docker-compose.yaml
```
here is my `docker compose` file

``` yaml
version: '3.8'
services:
  bun-server:
    container_name: bun-server
    restart: always
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - ${BUN_PORT}:${BUN_PORT}
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./data:/usr/src/app/data
    develop:
      watch:
        - action: sync
          path: ./server/src
          target: /usr/src/app/server/src
        - action: sync
          path: ./server/drizzle
          target: /usr/src/app/server/drizzle
        - action: rebuild
          path: ./server/package.json
  db:
    image: postgres
    container_name: postgres-db
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - ./db-data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes: 
  db-data:
```

here is the `docker file`

``` Dokerfile
FROM oven/bun:alpine

WORKDIR /usr/src/app/server

COPY package*.json ./
COPY bun.lockb ./

RUN bun install --frozen-lockfile

COPY ./src /usr/src/app/server/src

EXPOSE 5000

CMD [ "bun" , "run" , "dev"]
```

dev command is as follows
``` json
"dev": "bun run --hot src/index.ts",
```


so basically what this does is it watches for changes in your local env and persists it in the container instead of using volumes which will be mounted on to the container, watch command updates the files in the container hence bun will capture these changes and hot reload.
I read that docker compose watch doesn't use polling so it will be a better option
I don't have complete idea on how this works internally. But this method avoids the use of Chokidar or any other extra packages

I am new to writing such comments if there is some mistake correct me 😁😁

**Comment by KH93b** [comment]
volumes:
      - ./data:/usr/src/app/data
I think this is not necessary

**Comment by KH93b** [comment]
docker compose watch - this command does not display the server console.

a few time.. ))
docker compose up -> docker compose watch


EEEEEEEEEEESSSSSSSSSSSSSSSS   hot reload WORKS!!!!!!!!!!!

**Comment by AdityaT-19** [comment]
> ```
> volumes:
>   - ./data:/usr/src/app/data
> ```
> 
> I think this is not necessary

Ya this required because I have an ML app using the same data.

**Comment by AdityaT-19** [comment]
> docker compose watch - this command does not display the server console.
> 
> a few time.. )) docker compose up -> docker compose watch
> 
> EEEEEEEEEEESSSSSSSSSSSSSSSS hot reload is WORK!!!!!!!!!!!

docker compose up is not needed and you can check the logs in docker desktop 
I am happy that it worked.

**Comment by KH93b** [comment]
> docker compose up is not needed and you can check the logs in docker desktop I am happy that it worked.


I also use shared data, but it works for me without volume. Moreover, with volume I received a warning that watch will not work.

...
I understand that it will not be tracked if volume and watch refer to the same folder

**Comment by Drejerdk** [comment]
Anyone found a workaround for Minikube?

I have a host volume mounted to the containers, and when I can verify in the shells that files are updated in the pods, yet Bun doesn't detect it and reload.

Tried installing pm2 in the docker container, but it doesn't detect file changes from the host machine either.

**Comment by moshOntong-IT** [comment]
I found out that to reflect the changes you need to manually Control + S inside of your Docker then 

https://github.com/user-attachments/assets/1296b0de-ad73-473d-98f7-bb8f6a5c28ee

I hope this data can help you sir @Jarred-Sumner

**Comment by eduinlight** [comment]
This is how I use it for development and works.

```
services:
  server:
    container_name: replica-events-server
    image: oven/bun:1.1.30-alpine
    command: bun run --bun --watch ./src/server.ts
    working_dir: /home/bun/app
    user: "${UID}:${GID}"
    volumes:
      - .:/home/bun/app
      - ~/.bun-docker:/home/bun/.bun
    env_file:
      - .env
```

**Comment by moshOntong-IT** [comment]
> This is how I use it for development and works.
> 
> ```
> services:
>   server:
>     container_name: replica-events-server
>     image: oven/bun:1.1.30-alpine
>     command: bun run --bun --watch ./src/server.ts
>     working_dir: /home/bun/app
>     user: "${UID}:${GID}"
>     volumes:
>       - .:/home/bun/app
>       - ~/.bun-docker:/home/bun/.bun
>     env_file:
>       - .env
> ```

can you explain how does it work?

**Comment by eduinlight** [comment]
> > This is how I use it for development and works.
> > ```
> > services:
> >   server:
> >     container_name: replica-events-server
> >     image: oven/bun:1.1.30-alpine
> >     command: bun run --bun --watch ./src/server.ts
> >     working_dir: /home/bun/app
> >     user: "${UID}:${GID}"
> >     volumes:
> >       - .:/home/bun/app
> >       - ~/.bun-docker:/home/bun/.bun
> >     env_file:
> >       - .env
> > ```
> 
> can you explain how does it work?

Check my updated comment

**Comment by nicosql** [comment]
this is so fucking stupid

**Comment by eduinlight** [comment]
> > This is how I use it for development and works.
> > ```
> > services:
> >   server:
> >     container_name: replica-events-server
> >     image: oven/bun:1.1.30-alpine
> >     command: bun run --bun --watch ./src/server.ts
> >     working_dir: /home/bun/app
> >     user: "${UID}:${GID}"
> >     volumes:
> >       - .:/home/bun/app
> >       - ~/.bun-docker:/home/bun/.bun
> >     env_file:
> >       - .env
> > ```
> 
> can you explain how does it work?

I'm using the same user and group of my system inside the container. GID and UID are environment variables that exist in your system but if don't you can have it with `id -u` and `id -g` commands for user and group IDs. For any development container is important to match this two values to avoid wrong files permissions.

**Comment by lulezi** [comment]
I'm doing the same as @eduinlight and it doesn't work. Also tried with the latest bun version (1.1.42).

One thing I observed: If I edit the a file in the container directly, the live reload works fine. So it seems to not be missing the file system notifier but rather the connection to the host system.

**Comment by matej-kaska** [comment]
Still doesnt work in Bun 1.2.2, sad to see it, wanted to try Bun, but this is quite stupid...

**Comment by rg-lahcene** [comment]
I confirm it does not work on my Macbook 

![Image](https://github.com/user-attachments/assets/491a1b31-9e68-4099-8f6b-247187ba19ce)

**Comment by rynvelt** [comment]
Observing same behavior with bun 1.2.4 with docker-compose and WSL2

**Comment by francesco-loreti** [comment]
Same problem with bun 1.2.12 and WSL2

**Comment by edgeadjei** [comment]
I was able to get it working using `nodemon` but it's definitely not the ideal solution.
I've had nothing but great experiences working with bun! That said, tracking down a solution to this problem was a pain.
I'm not happy with the solution but i'm moving on focusing on my actual project. Hopefully the bun team can assist here.

**package.json**
```json
"scripts": {
  "dev": "nodemon --watch src --ext tsx,ts,js,html,css --exec 'bun src/server.tsx'",
  "dev:hot": "bun --hot src/server.tsx",
  "start": "NODE_ENV=production bun src/server.tsx",
  "build": "bun run build.ts"
}
```

**Dockerfile**
```Dockerfile
# Development stage
FROM base AS dev
# Copy dependencies from deps stage
COPY --from=deps /app/node_modules ./node_modules
# Install nodemon globally
RUN bun add -g nodemon
# Copy source code
COPY . .
# Expose port
EXPOSE 3000
# Start dev server with nodemon for file watching
CMD ["bun", "run", "dev"]
```

compose.yml
```yaml
environment:
  WATCHPACK_POLLING: true
  CHOKIDAR_USEPOLLING: true
```

**Comment by c4lliope** [comment]
I shared a couple opinions on this precise problem:
https://guide.operand.online/en/code/bundles

**Comment by csabaxyz** [comment]
I'm not 100% convinced that this is not a Bun issue. Not long ago I switched to Neovim and went down the rabbit hole, because all my Docker services stopped hot reloading. In the end I found out that the reason was Neovim's atomic updates, which essentially switched out the inodes on the files, so from that point on, the watchers lost the reference to files and stopped working.

Switching the `backupcopy` to `yes` in my Neovim config fixed this issue in my Node.js containers:
```lua
vim.opt.backupcopy = 'yes'
```

However, this still doesn't work in the Bun containers.

Here is a simple reproduction code:
```yaml
# compose.yaml
services:
  bun:
    image: oven/bun:1.3.10-alpine
    command: bun --watch index.js
    working_dir: /opt/src
    volumes:
      - .:/opt/src

  node:
    image: node:25.7.0-alpine
    command: node --watch index.js
    working_dir: /opt/src
    volumes:
      - .:/opt/src
```

```js
// index.js
import { createServer } from 'node:http'

const server = createServer((req, res) => {
  res.writeHead(200, { 'Content-Type': 'text/plain' })
  res.end('Hello World!\n')
})

server.listen(3000, '127.0.0.1', () => {
  console.log('Listening on 127.0.0.1:3000')
})

// console.log('Change')
```

After running `docker compose up`, you'll see that both services are running, however, if you uncomment the last line with the `console.log` and save, only the Node.js service will show the change.

```log
Attaching to bun-1, node-1
bun-1  | Listening on 127.0.0.1:3000
node-1  | Listening on 127.0.0.1:3000
node-1  | Restarting 'index.js'
node-1  | Change
node-1  | Listening on 127.0.0.1:3000
```

And if I `exec` into the Bun container and edit the file directly, then both services restart.
Also, if I change `backupcopy` to `no` in my Neovim config, then the Node.js service won't restart anymore either, so while I haven't looked into it, Node.js shouldn't use polling.

For reference, I'm using Colima with `virtiofs` on macOS, and `mountInofity` set to `true` (although it was the default when I installed Colima):
```yaml
# Default: virtiofs (for vz), sshfs (for qemu)
mountType: virtiofs

# Propagate inotify file events to the VM.
# NOTE: this is experimental.
mountInotify: true
```
