### ISSUE TITLE
prettier fails in Gitlab CI/CD in bun 1.0.5

### ISSUE THREAD

**Issue by sacummings91** [oven-sh/bun#6424]
### What version of Bun is running?

1.0.5+1bf28e0d77a8b2261befbdb708cefd03e0126960

### What platform is your computer?

Linux 5.4.109+ x86_64 unknown

### What steps can reproduce the bug?

I tried 3 different flavors of this and it failed all 3 times with 3 slightly different errors.

1. My actual command `"lint": "prettier -l 'src/{*,**/*}.ts' && eslint 'src/**/*.ts' && tsc --noEmit",` produces this error `/bin/bash: line 1:    19 Aborted                 (core dumped) prettier -l 'src/{*,**/*}.ts'
error: script "lint" exited with code 134`

```
test:
  stage: test
  image: oven/bun
  script:
    - bun i --frozen-lockfile
    - bun run lint
```

2. If you run a package.json script with `prettier -l 'src/{*,**/*}.ts'` by itself you get a slightly different error `error: script "reproduce" exited with code 6 (SIGABRT)`

```
test:
  stage: test
  image: oven/bun
  script:
    - bun i --frozen-lockfile
    - bun run foo
```

3. You can also run `bunx prettier -l 'src/{*,**/*}.ts'` but this fails with no error message

```
test:
  stage: test
  image: oven/bun
  script:
    - bun i --frozen-lockfile
    - bunx prettier -l 'src/{*,**/*}.ts'
```
    

### What is the expected behavior?

prettier should not fail

### What do you see instead?

prettier fails
