### ISSUE TITLE
Inconsistent package versions during CI package installation

### ISSUE THREAD

**Issue by fredericgrati** [oven-sh/bun#6480]
### What version of Bun is running?

1.0.6+969da088f5db3258a803ec186012e30f992829b4

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

Hello,

I have a problem regarding the installation of my packages in CI. 
Despite the following file:

```
name: Check

on:
  push:
    branches-ignore:
      - master

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
      - run: bun install --frozen-lockfile
      - run: ./node_modules/.bin/prettier -v
      - run: bun run check:prettier
```

The version displayed during installation is always prettier@3.0.3 (as specified in the lockfile).
![Screenshot 2023-10-13 at 14 06 48](https://github.com/oven-sh/bun/assets/1801383/4b160292-5eb2-4714-83bc-b1d695c78e30)

However, half of the time, when I check the installed version of prettier, I get prettier@2.8.8.

Is there a cache I need to clear, even though it's in a CI environment?

Thank you

### What is the expected behavior?

```
./node modules/.bin/prettier -v
3.0.3
```

### What do you see instead?

![Screenshot 2023-10-13 at 14 06 59](https://github.com/oven-sh/bun/assets/1801383/24ddd76e-dbf0-4cd9-80e8-979ef75f0c9e)

### Additional information

It works occasionally, so I suspect it might be a cache issue. 
However, deleting the cache to ensure the correct version seems like a workaround. Despite requesting a specific version, the system displays that version as installed, but in reality, it installs a different one.
