### ISSUE TITLE
bun --bun run dev fails with SvelteKit

### ISSUE THREAD

**Issue by debuxxed** [oven-sh/bun#6536]
### What version of Bun is running?

1.0.6+969da088f5db3258a803ec186012e30f992829b4

### What platform is your computer?

Linux 6.5.7-zen1-1-zen x86_64 unknown

### What steps can reproduce the bug?

1. Following [this](https://bun.sh/guides/ecosystem/sveltekit) tutorial to initialize project:
2. run project with `bun --bun run dev`
3. Change some stuff (in my case, i've been setting up main font in `global.css`:
```css
@import url('https://fonts.googleapis.com/css?family=Fira+Code&display=swap');

:root {
  --text: #eae9fc;
  --background: #040311;
  --primary: #8b7eec;
  --secondary: #130c41;
  --accent: #3620d9;
}

body {
  font-family: 'Fira Code', serif;
  /*font-weight: 400;*/
}

h1, h2, h3, h4, h5 {
  font-family: 'Fira Code', serif;
  /*font-weight: 700;*/
}
```
4. Randomly get this error upon reloading the website in browser/saving changes

My package.json:
```json
{
	"name": "boogaloo",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"dev": "bun --bun run vite dev",
		"build": "bun --bun run vite build",
		"preview": "bun --bun run vite preview",
		"check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
		"check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch",
		"lint": "prettier --plugin-search-dir . --check . && eslint .",
		"format": "prettier --plugin-search-dir . --write ."
	},
	"devDependencies": {
		"@sveltejs/adapter-auto": "^2.0.0",
		"@sveltejs/kit": "^1.20.4",
		"@typescript-eslint/eslint-plugin": "^6.0.0",
		"@typescript-eslint/parser": "^6.0.0",
		"bun-types": "^1.0.6",
		"eslint": "^8.28.0",
		"eslint-config-prettier": "^8.5.0",
		"eslint-plugin-svelte": "^2.30.0",
		"prettier": "^2.8.0",
		"prettier-plugin-svelte": "^2.10.1",
		"svelte": "^4.0.5",
		"svelte-adapter-bun": "^0.5.0",
		"svelte-check": "^3.4.3",
		"tslib": "^2.4.1",
		"typescript": "^5.0.0",
		"vite": "^4.4.2"
	},
	"type": "module"
}
```

### What do you see instead?

```
11:55:26 PM [vite] page reload src/lib/app/global.css
11:55:31 PM [vite] page reload src/lib/app/global.css (x2)
11:55:33 PM [vite] page reload src/lib/app/global.css (x3)
error: "vite" exited with code 11 (SIGSEGV)
```
