### ISSUE TITLE
Bun often (but not always) uses wrong Prettier package version in CI Azure DevOps pipeline

### ISSUE THREAD

**Issue by ItsJPrentice** [oven-sh/bun#6921]
### What version of Bun is running?

1.0.9+98f20170a

### What platform is your computer?

Linux 6.2.0-1015-azure x86_64 x86_64

### What steps can reproduce the bug?

I've configured a CI pipeline in Azure DevOps that installs Bun and my project dependencies and then runs multiple linters, including Prettier.

`package.json`
``` json
"scripts": {
  "lint": "bun lint:types && bun lint:scripts && bun lint:styles && bun lint:formatting",
  "lint:types": "tsc --noEmit",
  "lint:scripts": "next lint",
  "lint:styles": "stylelint \"**/*.{css,scss}\"",
  "lint:formatting": "prettier --check .",
},
"devDependencies": {
   "prettier": "^3.0.3",
}
```
`azure-pipelines.yml`
``` yml
steps:
  - script: curl -fsSL https://bun.sh/install | bash
    displayName: 🌰 Install Bun
  - script: echo "##vso[task.prependpath]$HOME/.bun/bin"
    displayName: ✏ Add Bun to PATH
  - script: bun install
    displayName: 📦 Install Packages
  - script: bun prettier --version
    displayName: 📐 Check Prettier Version
  - script: bun lint
    displayName: 🧹 Lint
```

The build fails frequently, but not always. To debug, I added the step `bun prettier --version` and noticed a difference in versions, depends on success or failure.

On successful builds, version `3.0.3` is returned. On failed builds, version `2.8.8` is returned.

Both of these version numbers match to entries in yarn.lock that's dumped when I run `bun install --yarn`
`yarn.lock`
```
prettier@^2.8.0:
  version "2.8.8"
  resolved "https://registry.npmjs.org/prettier/-/prettier-2.8.8.tgz"
  integrity sha512-tdN8qQGvNjw4CHbY+XXk0JgCXn9QiF21a55rBe5LJAU+kDyC4WQn4+awm2Xfk2lQMk5fKup9XgzTZtGkjBdP9Q==

prettier@^3.0.3:
  version "3.0.3"
  resolved "https://registry.npmjs.org/prettier/-/prettier-3.0.3.tgz"
  integrity sha512-L/4pUDMxcNa8R/EthV08Zt42WBO4h1rarVtK0K+QJG0X187OLo7l699jWw0GKuwzkPQ//jMFA/8Xm6Fh3J/DAg==
```

`3.0.3` is a configured project dev dependency. `2.8.8`, is a nested dependency of the packages `@storybook/codemod` and `@storybook/cli`.

### What is the expected behavior?

My expectation is that executing the command `bun prettier --version` in CI would always return the version `3.0.3` given that's the newer version and a configured project dev dependency.

### What do you see instead?

More often than not, version `2.8.8` is returned.

### Additional information

I can't reproduce this behavior locally.
