### ISSUE TITLE
It is impossible do inspect Bun application inside docker using vscode

### ISSUE THREAD

**Issue by matepaiva** [oven-sh/bun#7490]
### What version of Bun is running?

docker oven/bun:1-slim

### What platform is your computer?

docker

### What steps can reproduce the bug?

1. create a simple bun application.
2. add a script to your package.json like `"watch": "bun --hot --inspect=ws://0.0.0.0:6499/forcingPrefix index.ts "`
3. create a Dockerfile to run it, like:
```
FROM oven/bun:1-slim as base
COPY . .
RUN bun install

USER bun

ENV NODE_ENV=development

EXPOSE 3000/tcp
EXPOSE 6499/tcp

CMD ["bun", "watch"]
```
4. create a docker-compose.yaml, like:
```
version: "3.8"

services:
  bun-app:
    build: ./html-to-image-bun-server
    ports:
      - "3001:3000"
      - "6499:6499"
    expose:
      - 6499
    volumes:
      - ./html-to-image-bun-server:/home/bun/app
```
5. run `docker compose up`
6. create a `.vscode/launch.json` like:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "bun",
      "request": "attach",
      "name": "Attach to Bun",
      "url": "ws://127.0.0.1:6499/forcingPrefix",      
    }
  ]
}
```
7. start debugging via vscode using "Attach to Bun" option. It starts fine.
8. add a breakpoint to any line and do something (a request) to run that line. It will not stop at the line, but it should! ❌ 

### What is the expected behavior?

I should be able to inspect a bun application inside a docker via websocket, but it does not work as supposed.

### What do you see instead?

I can inspect it using the web bun debugger, but it does not work at vscode.

### Additional information

Instead of "0.0.0.0", I tried to pass different values to inspect (at package.json and at launch.json), like "localhost" or "127.0.0.1". It does not work.
