### ISSUE TITLE
`bun install` broke since v1.0.17: /usr/bin/bash: line 1: node-gyp: command not found

### ISSUE THREAD

**Issue by tigitz** [oven-sh/bun#7598]
### What version of Bun is running?

v1.0.17

### What platform is your computer?

Github CI

### What steps can reproduce the bug?

Use this github CI workflow:
```yaml
jobs:
  scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install deps
        run: bun install
 ```
 
 And this package.json
 
 ```json
{
  "dependencies": {
    "@percy/cli-command": "^1.27.2",
    "dotenv": "^16.3.1",
    "execa": "^8.0.1",
    "node-ssh": "^13.1.0"
  }
}
 ```

### What is the expected behavior?

![image](https://github.com/oven-sh/bun/assets/1524501/cef69182-733b-4ed0-b11d-11fae70ac193)

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/1524501/08676061-bedf-4743-bd40-589b082f8a63)

**Comment by MYKEU** [comment]
Same thing happening for me - had to downgrade to `1.0.16`

**Comment by sarahkadar** [comment]
Same here. I was so excited to finally use Bun on one of our projects since it supports post-install scripts — and it worked fine on my mac, but breaks in our CI.

**Comment by r0ld3x** [comment]
try this


```
      - name: Install items
        run: sudo apt-get update && sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev -y
      - name: Install node-gyp
        run:  sudo bun i node-gyp
```

or check #7599

**Comment by 3w36zj6** [comment]
The following code is a temporary solution:

```yaml
- uses: oven-sh/setup-bun@v1
  with:
    bun-version: 1.0.16
```
