### ISSUE TITLE
The performance of the `bun install` has been degraded in 1.0.17 in github actions

### ISSUE THREAD

**Issue by tonypinkevych** [oven-sh/bun#7689]
### What version of Bun is running?

1.0.17

### What platform is your computer?

ubuntu-latest

### What steps can reproduce the bug?

Create simple github action and just add `bun install` step.

```yml
name: Simple bun install reproducable

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.0.17' # if you set here `1.0.16` then everything works fine

      - name: Install dependencies
        run: bun install
```

### What is the expected behavior?

It installs in 15-20 seconds, just like before. Find video below.

https://github.com/oven-sh/bun/assets/13913581/ffa21cfa-4b5e-40ba-9be7-b86295ab776e

### What do you see instead?

It holds for 90+ seconds on `bun install v1.0.17` row. Find video below.

https://github.com/oven-sh/bun/assets/13913581/6764fec8-37e4-4ada-8f81-16b76db09cfc

### Additional information

Perhaps the problem is related to this update: https://bun.sh/blog/bun-v1.0.17#bun-install-now-runs-lifecycle-scripts-for-the-top-500-npm-packages. But it worked fine before that.
I hope you can find a solution to make it fast, but still run the necessary scripts.

Hope this helps.
