### ISSUE TITLE
Error: Cannot find module 'detect-libc'

### ISSUE THREAD

**Issue by ollecoffee** [oven-sh/bun#7729]
### What version of Bun is running?

 bun install v1.0.18 (36c316a2)

### What platform is your computer?

Github Actions

### What steps can reproduce the bug?
Using astro :) 
```ts
bun install v1.0.18 (36c316a2)
node:internal/modules/cjs/loader:1137
  throw err;
  ^

Error: Cannot find module 'detect-libc'
Require stack:
- /home/runner/work/olle.coffee/olle.coffee/node_modules/astro/node_modules/sharp/install/libvips.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/home/runner/work/olle.coffee/olle.coffee/node_modules/astro/node_modules/sharp/install/libvips.js:13:20)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/olle.coffee/olle.coffee/node_modules/astro/node_modules/sharp/install/libvips.js'
  ]
}
```

### What is the expected behavior?

https://github.com/ollegkz/olle.coffee/actions/runs/7259256409

### What do you see instead?

https://github.com/ollegkz/olle.coffee/actions/runs/7259394812

### Additional information

running bun install twice seems to solve it, see https://github.com/ollegkz/olle.coffee/commit/f32053cb2166ebf0d1c3e3f239e763401a2b6ea5

**Comment by ollecoffee** [comment]
Didn't help with two installs :( https://github.com/ollegkz/olle.coffee/actions/runs/7264836340

**Comment by paperclover** [comment]
this is a node.js stack trace. re-run with `bun --bun astro build

**Comment by ollecoffee** [comment]
So the solution is for withastro/action@v1 to use --bun? :) https://github.com/withastro/action/blob/main/action.yml#L93

**Comment by zanhk** [comment]
Same error as well, it happen sometimes, not consinstely

here's my workflow

```yaml
name: Assertions and static report

on:
    workflow_dispatch:
    push:
        branches:
            - main

env:
    PRIVJS_TOKEN: ${{ secrets.PRIVJS_TOKEN }}

jobs:
    test-and-deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v3

            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Install Global dependencies
              run: bun install -g netlify-cli @unlighthouse/cli puppeteer

            - name: Unlighthouse assertions and client
              run: unlighthouse-ci

            - name: Deploy
              run: netlify deploy --dir=.unlighthouse --prod --message="New Release Deploy from GitHub Actions"
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
```

here the error stack:

```
Run bun install
bun install v1.0.22 (b400b3[6](https://github.com/majesticostudio/majestico.it/actions/runs/7532921476/job/20504464338#step:4:7)c)
node:internal/modules/cjs/loader:113[7](https://github.com/majesticostudio/majestico.it/actions/runs/7532921476/job/20504464338#step:4:8)
  throw err;
  ^

Error: Cannot find module 'detect-libc'
Require stack:
- /home/runner/work/majestico.it/majestico.it/node_modules/@vite-pwa/assets-generator/node_modules/sharp/install/libvips.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:1[8](https://github.com/majesticostudio/majestico.it/actions/runs/7532921476/job/20504464338#step:4:9))
    at Object.<anonymous> (/home/runner/work/majestico.it/majestico.it/node_modules/@vite-pwa/assets-generator/node_modules/sharp/install/libvips.js:13:20)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:11[9](https://github.com/majesticostudio/majestico.it/actions/runs/7532921476/job/20504464338#step:4:10)7:32)
    at Module._load (node:internal/modules/cjs/loader:[10](https://github.com/majesticostudio/majestico.it/actions/runs/7532921476/job/20504464338#step:4:11)13:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/majestico.it/majestico.it/node_modules/@vite-pwa/assets-generator/node_modules/sharp/install/libvips.js'
  ]
}

Node.js v18.19.0
node:internal/modules/cjs/loader:[11](https://github.com/majesticostudio/majestico.it/actions/runs/7532921476/job/20504464338#step:4:12)37
  throw err;
  ^

Error: Cannot find module 'semver/functions/coerce'
Require stack:
- /home/runner/work/majestico.it/majestico.it/node_modules/@vite-pwa/assets-generator/node_modules/sharp/lib/libvips.js
- /home/runner/work/majestico.it/majestico.it/node_modules/@vite-pwa/assets-generator/node_modules/sharp/install/can-compile.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:[12](https://github.com/majesticostudio/majestico.it/actions/runs/7532921476/job/20504464338#step:4:13)25:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/home/runner/work/majestico.it/majestico.it/node_modules/@vite-pwa/assets-generator/node_modules/sharp/lib/libvips.js:10:22)
    at Module._compile (node:internal/modules/cjs/loader:[13](https://github.com/majesticostudio/majestico.it/actions/runs/7532921476/job/20504464338#step:4:14)56:[14](https://github.com/majesticostudio/majestico.it/actions/runs/7532921476/job/20504464338#step:4:15))
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/majestico.it/majestico.it/node_modules/@vite-pwa/assets-generator/node_modules/sharp/lib/libvips.js',
    '/home/runner/work/majestico.it/majestico.it/node_modules/@vite-pwa/assets-generator/node_modules/sharp/install/can-compile.js'
  ]
}

Node.js v[18](https://github.com/majesticostudio/majestico.it/actions/runs/7532921476/job/20504464338#step:4:19).[19](https://github.com/majesticostudio/majestico.it/actions/runs/7532921476/job/20504464338#step:4:20).0

error: install script from "sharp" exited with 1
Error: Process completed with exit code 1.
```

Never got problems locally (yet)
