### ISSUE TITLE
Bun does not expand environment variables in bunfig.toml

### ISSUE THREAD

**Issue by khromov** [oven-sh/bun#9541]
### What version of Bun is running?

1.0.33+9e91e137f

### What platform is your computer?

Mac ARM

### What steps can reproduce the bug?

I've been having a really hard time to get Bun to read environment variables. 

I have this bunfig.toml:

```
[install.registry]
url = "https://artifacts.company.io/artifactory/api/npm/npm-virtual/:_auth=$ARTIFACTORY_NPM_SECRET"
```

This will not work regardless of the fact that the environment variable is set:

```
echo $ARTIFACTORY_NPM_SECRET
123....
```

I also tried putting it in `.env` either like this:

```
ARTIFACTORY_NPM_SECRET=123...
```

Or like this:

```
ARTIFACTORY_NPM_SECRET=${ARTIFACTORY_NPM_SECRET}
```

But neither of the above works.

I have confirmed that if I hard code the variable in bunfig it *does* work. I just need Bun to read the (preferably) actual environment variable (from process.env).

This works, but I can't use it: 

```
[install.registry]
url = "https://artifacts.company.io/artifactory/api/npm/npm-virtual/:_auth=123..."
```

I did a bit of debugging and it does indeed look like the variable isn't expanded, after running `bun i` and logging the request:

```
[Wed Mar 20 17:18:48 2024] {"Authorization":"Basic $ARTIFACTORY_NPM_SECRET","npm-auth-type":"legacy","If-None-Match":"26bf6e7a780b37287fe581c26bc132bc30f93956","Accept":"application\/vnd.npm.install-v1+json; q=1.0, application\/json; q=0.8, *\/*","Connection":"keep-alive","User-Agent":"Bun\/1.0.33","Host":"127.0.0.1:8089","Accept-Encoding":"gzip, deflate, br"}
```

### What is the expected behavior?

bunfig.toml should expand both real environment variables and those in .env files.

### What do you see instead?

-

### Additional information

-

**Comment by juliankoehn** [comment]
we are missing the environment variables too!

```
# macOS sonoma
# Bun 1.1
bun run env
```

does not include `.env`

Works with bun 1.0.29

**Comment by TroyAlford-RL** [comment]
I have had some success working around this issue by using this syntax:
```toml
[install.registry]
url = "https://<your_domain>.jfrog.io/artifactory/api/npm/<your_repository>/"
token = "$TOKEN"

[install.scopes]
"@your_scope" = {
  url = "https://<your_domain>.jfrog.io/artifactory/api/npm/<your_repository>/",
  token = "$ART_TOKEN"
}
```
(substituting the `<your_*>` keys with appropriate values, of course)

The docs at https://bun.sh/guides/install/jfrog-artifactory show this, as of today:
<img width="714" alt="image" src="https://github.com/oven-sh/bun/assets/104388507/d74f21e0-4846-4843-9a2e-fa54e3e0d73c">

As far as I can tell, this syntax simply doesn't work at the moment, but splitting the `token` into a separate variable in the `TOML` does. I'm unclear if setting `username` or `password` instead of `token` would work, as we use tokens in my scenario.

**Comment by khromov** [comment]
Thanks, I confirmed that substitution of `url` works as expected , but it would be really great to be able to substitute inside `url` as well.

Edit: After some testing, I concluded that _auth is equivalent to base64-encoded basic auth and you can set it using username/password using:

```toml
[install.registry]
url = "http://localhost:8080/artifactory/api/npm/npm-virtual/"
username="$USERNAME"
password="$PWD"
```
