### ISSUE TITLE
Bun install sometimes fails in Github actions

### ISSUE THREAD

**Issue by Micnubinub** [oven-sh/bun#9699]
### What version of Bun is running?

1.0.35

### What platform is your computer?

Linux 6.5.0-1016-azure x86_64 x86_64 (Github actions ubuntu-latest) 

### What steps can reproduce the bug?

Just a github action that reacts to a push

```
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun Runtime
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.35

      - run: bun install
```

### What is the expected behavior?

Packages to install without issues... The fix is just rerunning, usually once, but sometimes takes up to 3 reruns

### What do you see instead?

Error messages are always about a package out being found
```
bun install v1.0.35 (940448d6)
node:internal/modules/cjs/loader:1137
  throw err;
  ^

Error: Cannot find module 'tar-fs'
...Stack...

Node.js v18.19.1

error: install script from "sharp" exited with 1
Error: Process completed with exit code 1.
```

Insert package where is says `tar-fs`, but always related to sharp. Just rerunning the job fixes it

### Additional information

Doesn't always happen, sharp v0.33.3
