### ISSUE TITLE
BUN_HOME env variable for bun

### ISSUE THREAD

**Issue by MMMMMoris** [oven-sh/bun#9999]
### What is the type of issue?

Documentation is confusing

## Firstly, .bunfig.toml seems unable to work on Windows
Here is my config
```toml
[install.cache]
# the directory to use for the cache
dir = "~/AppData/Local/Temp/bun/install/cache"

# when true, don't load from the global cache.
# Bun may still write to node_modules/.cache
disable = false

# when true, always resolve the latest versions from the registry
disableManifest = false
```
Command `bun install -g live-server` still installed live-server in `~/.bun`, downloaded files cached in it as well.

## Secondly, can bun install packages through the value of  env variable `$BUN_HOME `?
Just like many other program will do, set up a `$PROGRAM_HOME` env variable, and make modification under that very path only.
Like `$JAVA_HOME`, `$GOPATH`, `$GOCACHE`
To be honest, I don't want A .bun folder existing in my Home Folder, there is a .dev folder I set up for program tools specifically.
